sgs::controller::GridController
final GridMapListener sgs.controller.GridController.gridMapListener
Referenced by sgs.controller.GridController.GridController.
final SgsGridModel sgs.controller.GridController.gridModel
Referenced by sgs.controller.GridController.GridController, sgs.controller.GridController.addGridObject, sgs.controller.GridController.calculatePowerLines, sgs.controller.GridController.closeAllObjectParameterWindows, sgs.controller.GridController.deleteGridObject, sgs.controller.GridController.getCellStatus, sgs.controller.GridController.getDirectNeighborsFrom, sgs.controller.GridController.getModel, sgs.controller.GridController.refreshAllObjectParameterWindows.
final ColorOverlayController sgs.controller.GridController.colorOverlayController
int [] sgs.controller.GridController.tempRememberMarkObject
Referenced by sgs.controller.GridController.actionfor_pasteCopiedObject, sgs.controller.GridController.actionfor_copyGridObject.
UndoManager sgs.controller.GridController.undoManager
Referenced by sgs.controller.GridController.setUndoManager, sgs.controller.GridController.actionfor_undo, sgs.controller.GridController.actionfor_redo.
SmartGridObject sgs.controller.GridController.copyObject
sgs.controller.GridController.GridController(SgsGridModel gridModel, PrimaryViewI view)
Constructor: Creates GridMapListener.Loads Object Images. gridModel view
References sgs.controller.GridController.gridModel, sgs.controller.GridController.gridMapListener.
void sgs.controller.GridController.actionfor_pasteCopiedObject()
References sgs.controller.GridController.tempRememberMarkObject, sgs.controller.GridController.addGridObject, sgs.model.gridObjects.SmartGridObject.factory, sgs.model.gridObjects.SmartGridObject.getEnum.
void sgs.controller.GridController.addGridObject(GridDataEnum enu, int x, int y)
Add an grid object with it's corresponding enum. Initializes the object with the choosen model enu - enum for an SmartSimObject x - new coordinate y - new coordinate
References sgs.model.gridData.GridDataEnum.getMappedModel, sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.modelConstructor, sgs.model.gridData.GridDataEnum.getMappedClass.
Referenced by sgs.controller.GridController.actionfor_pasteCopiedObject.
SmartGridObject sgs.controller.GridController.addGridObject(SmartGridObject sso, int x, int y)
Add an grid object directly. enu - enum for an SmartSimObject x - new coordinate y - new coordinate
References sgs.model.gridData.GridDataEnum.Type.MAP_LRUD, sgs.controller.GridController.calculatePowerLines.
void sgs.controller.GridController.calculatePowerLines(int x, int y, int checkNeighbours)
x y checkNeighbours
References sgs.controller.GridController.calculateSupraLines, sgs.controller.GridController.getCellStatus, sgs.model.gridData.GridDataEnum.Type.MAP_UD, sgs.model.gridData.GridDataEnum.Type.MAP_LR, sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.getNrOfCellsWidth, sgs.model.SgsGridModel.getNrOfCellsHeight.
Referenced by sgs.controller.GridController.addGridObject, sgs.controller.GridController.calculateSupraLines, sgs.controller.GridController.deleteGridObject.
void sgs.controller.GridController.calculateSupraLines(int x, int y, int CheckNeighbours)
x y CheckNeighbours
References sgs.controller.GridController.getCellStatus, sgs.model.gridData.GridDataEnum.Type.MAP_UD, sgs.model.gridData.GridDataEnum.Type.MAP_LR, sgs.model.gridData.GridDataEnum.Type.MAP_RU, sgs.model.gridData.GridDataEnum.Type.MAP_LU, sgs.model.gridData.GridDataEnum.Type.MAP_RD, sgs.model.gridData.GridDataEnum.Type.MAP_LD, sgs.model.gridData.GridDataEnum.Type.MAP_RUD, sgs.model.gridData.GridDataEnum.Type.MAP_LUD, sgs.model.gridData.GridDataEnum.Type.MAP_LRU, sgs.model.gridData.GridDataEnum.Type.MAP_LRD, sgs.model.gridData.GridDataEnum.Type.MAP_LRUD, sgs.controller.GridController.calculatePowerLines.
Referenced by sgs.controller.GridController.calculatePowerLines.
void sgs.controller.GridController.clearGrid()
void sgs.controller.GridController.closeAllObjectParameterWindows()
Closes all opened parameter windows.
References sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.gridObjectList.
void sgs.controller.GridController.actionfor_copyGridObject()
References sgs.controller.GridController.tempRememberMarkObject.
Referenced by sgs.controller.GridController.actionfor_cutOffObject.
void sgs.controller.GridController.actionfor_deleteObject()
gridController action for deleting an object from the grid this method only deletes an object wich has a mark on it.
References sgs.controller.GridController.deleteGridObject.
Referenced by sgs.controller.GridController.actionfor_cutOffObject.
void sgs.controller.GridController.actionfor_cutOffObject()
gridController action for cut off an object from the grid.
References sgs.controller.GridController.actionfor_copyGridObject, sgs.controller.GridController.actionfor_deleteObject.
void sgs.controller.GridController.deleteGridObject(int x, int y)
Delete an instance in the JGM at the coordinates. In 2D Object Array, 2D ID Array and 1D List. x y
References sgs.controller.GridController.gridModel, sgs.controller.GridController.calculatePowerLines.
Referenced by sgs.controller.GridController.actionfor_deleteObject.
LinkedList<SmartGridObject> sgs.controller.GridController.getAllNeighborsFrom(LinkedList< SmartGridObject > toVisit, SmartGridObject sgo)
toVisit - only these objects will be used. Null = use all grid objects sgo - start point all neighbors from object and from the neighbors of neighbors.
References sgs.controller.GridController.getDirectNeighborsFrom.
boolean sgs.controller.GridController.getCellStatus(int x, int y)
Doesn't just read the array but checks if it's out of the array. Furthermore, this returns true if it's not empty. x y true if coordinate is not empty, false in all other cases.
References sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.getNrOfCellsWidth, sgs.model.SgsGridModel.getNrOfCellsHeight.
Referenced by sgs.controller.GridController.calculatePowerLines, sgs.controller.GridController.calculateSupraLines.
LinkedList<SmartGridObject> sgs.controller.GridController.getDirectNeighborsFrom(LinkedList< SmartGridObject > toVisit, SmartGridObject sgo)
Based on all SmartGridObjects in Model. toVisit - only these objects will be used. Found objects will be removed. Null = use all grid objects List of neighbors which were in the list
References sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.getNrOfCellsWidth, sgs.model.SgsGridModel.getNrOfCellsHeight.
Referenced by sgs.controller.GridController.getAllNeighborsFrom, sgs.controller.GridController.getDirectNeighborsFrom.
LinkedList<SmartGridObject> sgs.controller.GridController.getDirectNeighborsFrom(LinkedList< SmartGridObject > notVisited, LinkedList< SmartGridObject > startObjects)
notVisited - only these objects will be "visited", may also be startObjects. null... use all grid objects EXCLUDING startObjects. startObjects - objects to start from (normally a cluster of objects), not changed List with direct neighbors of objects in sgos.
References sgs.controller.GridController.getDirectNeighborsFrom.
SgsGridModel sgs.controller.GridController.getModel()
References sgs.controller.GridController.gridModel.
void sgs.controller.GridController.refreshAllObjectParameterWindows()
Closes all opened parameter windows.
References sgs.controller.GridController.gridModel, sgs.model.SgsGridModel.gridObjectList, sgs.model.gridObjects.SmartGridObject.ownedWindows.
void sgs.controller.GridController.setUndoManager(UndoManager undoManager)
Sabrina Huber received from the PrimaryController an UndoManger, Set the correct undo manager undoManager
References sgs.controller.GridController.undoManager.
void sgs.controller.GridController.actionfor_undo()
References sgs.controller.GridController.undoManager.
void sgs.controller.GridController.actionfor_redo()
References sgs.controller.GridController.undoManager.
void sgs.controller.GridController.addNeighborsFrom(LinkedList< SmartGridObject > notVisited, int x, int y, LinkedList< SmartGridObject > neighbours)
notVisited - visited objects will be removed. Use all GridObjects if toVisit==null x - coordinate of the object y - ... neighbours - list where to add neighbors
void sgs.controller.GridController.setSavedSmartGridObject(SmartGridObject sso)
SmartGridObject sgs.controller.GridController.getSavedSmartGridObject()
void sgs.controller.GridController.initGridData()
Set every position to "EMPTY"
static void sgs.controller.GridController.loadImagesNew(JGridMap jgm)
New JGM image loading function jgm
static void sgs.controller.GridController.loadEnumImages(JGridMap jgm, GridDataEnum gridDataEnum)
Load data for a single jgm gridDataEnum