sgs::controller::simulation::calculation::GaussSeidelPFSolver
NumericValue sgs.controller.simulation.calculation.GaussSeidelPFSolver.Y[][][][]
NumericValue sgs.controller.simulation.calculation.GaussSeidelPFSolver.P[][]
NumericValue sgs.controller.simulation.calculation.GaussSeidelPFSolver.U[][]
ACPowerFlowCalculator.busTypes [] sgs.controller.simulation.calculation.GaussSeidelPFSolver.busTypes
int sgs.controller.simulation.calculation.GaussSeidelPFSolver.noOfBuses
int sgs.controller.simulation.calculation.GaussSeidelPFSolver.swingIndex
boolean sgs.controller.simulation.calculation.GaussSeidelPFSolver.errorMessageSend
double sgs.controller.simulation.calculation.GaussSeidelPFSolver.confergenceAcuracy
int sgs.controller.simulation.calculation.GaussSeidelPFSolver.maximumIterations
double sgs.controller.simulation.calculation.GaussSeidelPFSolver.scaleFactor
NumericValue sgs.controller.simulation.calculation.GaussSeidelPFSolver.DEFAULT_VALUE
final double sgs.controller.simulation.calculation.GaussSeidelPFSolver.d2r
final double sgs.controller.simulation.calculation.GaussSeidelPFSolver.w
sgs.controller.simulation.calculation.GaussSeidelPFSolver.GaussSeidelPFSolver()
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.solve()
Solves the AC-Power-Flow Problem by using the iterative Gauss-Seidel-Method Bus-Voltage is set to 1.0 initial For every load bus, the voltage is calculated For every generator bus, the Voltage angle and Reactive Power are calculated For every reference bus, real and reactive power are calculated Exception
References sgs.model.variables.NumericValue.copy, sgs.model.variables.NumericValue.abs.
double sgs.controller.simulation.calculation.GaussSeidelPFSolver.getScaleFactor()
Referenced by sgs.controller.simulation.ACPowerFlowCalculator.calculationStep.
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.setAdmittanceMatrix(NumericValue[][] y)
NumericValue [][] sgs.controller.simulation.calculation.GaussSeidelPFSolver.getAdmittanceMatrix()
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.setPowerVector(NumericValue[] pq)
NumericValue [] sgs.controller.simulation.calculation.GaussSeidelPFSolver.getPowerVector()
Referenced by sgs.controller.simulation.ACPowerFlowCalculator.calculationStep.
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.setVoltageVector(NumericValue[] u2)
NumericValue [] sgs.controller.simulation.calculation.GaussSeidelPFSolver.getVoltageVector()
Referenced by sgs.controller.simulation.ACPowerFlowCalculator.calculationStep.
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.setBusTypes(ACPowerFlowCalculator.busTypes[] bT)
ACPowerFlowCalculator.busTypes [] sgs.controller.simulation.calculation.GaussSeidelPFSolver.getBusTypes()
busTypes
double sgs.controller.simulation.calculation.GaussSeidelPFSolver.calcScaleExponent()
cnt
void sgs.controller.simulation.calculation.GaussSeidelPFSolver.writeBackPandU(NumericValue[] p, NumericValue[] u)
p u
NumericValue sgs.controller.simulation.calculation.GaussSeidelPFSolver.roundCtoNumVal(NumericValue value)
value NumericValue(tmp)