sgs::model::variables::SingleVariable
final String sgs.model.variables.SingleVariable.name
AbstractValue sgs.model.variables.SingleVariable.value
EnumUnit sgs.model.variables.SingleVariable.unit
VariableProperties sgs.model.variables.SingleVariable.properties
Referenced by sgs.model.variables.SingleVariable.variableIsUsed, sgs.model.variables.VariableSet.isUsed, sgs.model.variables.VariableSet.getVisibles.
sgs.model.variables.SingleVariable.SingleVariable(String name, AbstractValue value, EnumUnit unit)
Constructor: only for use in Models - not in Objects name value unit ModelVariable
References sgs.model.variables.SingleVariable.name, sgs.model.variables.SingleVariable.value, sgs.model.variables.SingleVariable.unit.
Referenced by sgs.model.variables.SingleVariable.copyKeepProperties.
sgs.model.variables.SingleVariable.SingleVariable(EnumPV name, AbstractValue value)
Constructor: for EnumPV types name value unit
References sgs.model.variables.EnumPV.getUnit.
String sgs.model.variables.SingleVariable.name()
the variable name
Referenced by sgs.model.variables.SingleVariable.SingleVariable, sgs.model.variables.SingleVariable.copyKeepProperties, sgs.model.variables.SingleVariable.toString.
AbstractValue sgs.model.variables.SingleVariable.value()
the value object, containing the actual variable value
Referenced by sgs.model.variables.SingleVariable.SingleVariable.
EnumUnit sgs.model.variables.SingleVariable.unit()
the unit, describing the variable and its value
Referenced by sgs.model.variables.SingleVariable.SingleVariable, sgs.model.variables.SingleVariable.copyKeepProperties, sgs.model.variables.SingleVariable.toString.
Double sgs.model.variables.SingleVariable.getValueString()
the value of the variable as String.
Double sgs.model.variables.SingleVariable.getValueDouble()
the double value of the variable, zero for non numeric values.
Referenced by sgs.model.objectModels.FossilFuelModel.updateVariables, sgs.model.objectModels.RandomWindTurbineModel.updateVariables, sgs.model.objectModels.SolarPeakPowerModel.updateVariables, sgs.model.objectModels.SolarPeakPowerModel.initVariableSet, sgs.model.objectModels.SolarSquareMeterModel.updateVariables, sgs.model.objectModels.SolarSquareMeterModel.initVariableSet, sgs.model.objectModels.UsualWindTurbineModel.updateVariables.
Complex sgs.model.variables.SingleVariable.getValueComplex()
the Complex value of the variable, zero for non numeric values.
NumericValue sgs.model.variables.SingleVariable.getValueNumeric()
the numeric value, may be null for non numeric values.
void sgs.model.variables.SingleVariable.setValue(String val)
value
void sgs.model.variables.SingleVariable.setValue(double d)
Set double value. May not be compatible with every subclass of AbstractValue. d
void sgs.model.variables.SingleVariable.setValue(Complex c)
Set Complex value. May not be compatible with every subclass of AbstractValue. d
void sgs.model.variables.SingleVariable.setValue(NumericValue v)
Set Numeric value. May not be compatible with every subclass of AbstractValue. v
boolean sgs.model.variables.SingleVariable.variableIsUsed()
true if Variable isVisible OR isEditable (definition)
References sgs.model.variables.SingleVariable.properties.
int sgs.model.variables.SingleVariable.compareTo(SingleVariable attr2)
Implementation for TreeSet
Referenced by sgs.model.variables.VariableSet.get.
SingleVariable sgs.model.variables.SingleVariable.copyKeepProperties()
a deep Copy, except the properties.
References sgs.model.variables.SingleVariable.SingleVariable, sgs.model.variables.SingleVariable.name, sgs.model.variables.SingleVariable.unit.
String sgs.model.variables.SingleVariable.toString()
References sgs.model.variables.SingleVariable.name, sgs.model.variables.SingleVariable.unit.
sgs.model.variables.SingleVariable.SingleVariable(String name)
Constructor: internal use name
References sgs.model.variables.SingleVariable.name.