sgs::controller::simulation::AbstractDistributionAlgorithm
GridDataNode sgs.controller.simulation.AbstractDistributionAlgorithm.selectedNode
GridDataNode temporary used for setting algorithm specific variables
String sgs.controller.simulation.AbstractDistributionAlgorithm.description
Description of how the Algorithm works (to ease selection process in future)
OutputStream sgs.controller.simulation.AbstractDistributionAlgorithm.log
Log stream for logging data if activated. Can be null
Referenced by sgs.controller.simulation.AbstractDistributionAlgorithm.closeLog, sgs.controller.simulation.AbstractDistributionAlgorithm.log, sgs.controller.simulation.ACPowerFlowCalculator.calculationStep, sgs.controller.simulation.ACPowerFlowCalculator.simulationStarted, sgs.controller.simulation.DCPowerFlowCalculator.calculationStep, sgs.controller.simulation.SimplePowerDistribution.calculationStep, sgs.controller.simulation.SimplePowerDistribution.simulationStarted.
sgs.controller.simulation.AbstractDistributionAlgorithm.AbstractDistributionAlgorithm()
Constructor: initialize variables (visibility, properties) used in this algorithm. Note: Sub classes must have a Constructor with the parameter GridController for generating automated instances.
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.calculationStep()
Calculate grid for one simulation step. Buses and Paths are locked before. Grid/View-Repaint is automatically called after the function.
void sgs.controller.simulation.AbstractDistributionAlgorithm.initializeAlgorithm()
Initialize Algorithm specific settings and data.
Referenced by sgs.controller.simulation.AbstractDistributionAlgorithm.initializeFull.
void sgs.controller.simulation.AbstractDistributionAlgorithm.initializeFull()
Full initialization. Should be called if algorithm is used for the first time or the algorithm was changed.
References sgs.controller.simulation.AbstractDistributionAlgorithm.initializeAlgorithm.
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.gridChanged()
Is called if the Grid is modified.
String sgs.controller.simulation.AbstractDistributionAlgorithm.getName()
Get all the Transactions that have taken place the name of the algorithm
abstract String sgs.controller.simulation.AbstractDistributionAlgorithm.getDescription()
description of the specific algorithm used for the "Info" button
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.simulationStarted()
Called by time thread. Write interesting contents of the simulation to a file. Called directly after the simulation was started. Use this to make a LOG file if one is used.
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.simulationStopped()
Called directly after the simulation was stopped. Use this to flush/close a log file if one was used.
String sgs.controller.simulation.AbstractDistributionAlgorithm.generateList()
hs all classes who inherit this one, should have this method to create a String, to make the CSV-File
void sgs.controller.simulation.AbstractDistributionAlgorithm.initializeVariables()
Initialize the used Variables
void sgs.controller.simulation.AbstractDistributionAlgorithm.resetPropertiesForVariables()
Step 0: reset existing variable properties setPropertiesForVariables(), initializeVariables()
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.setPropertiesForVariables()
Set the algorithm specific variables with help of the super class methods. selectClass(Class), setProperties(boolean,boolean,EnumPV[]), initializeVariables()
void sgs.controller.simulation.AbstractDistributionAlgorithm.selectClass(Class<?extends SmartGridObject > selectedClass)
Step 1: Select class for enabling variables c setPropertiesForVariables()
void sgs.controller.simulation.AbstractDistributionAlgorithm.setProperties(boolean visible, boolean editable, EnumPV...variables)
Step 2: Enable variables with their properties. Sets properties for selected class and its sub classes. visible - the variable is visible to the user editable - the variable is editable for the user variables - variables where specified properties should be set setPropertiesForVariables()
References sgs.model.gridData.GridDataNode.nodeVariableSet.
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.setPropertiesForBusAndPath()
Set SgsGridModel.resistanceAttributes, busVariableCollection, pathVariableCollection if used.
abstract void sgs.controller.simulation.AbstractDistributionAlgorithm.unloadAlgorithm()
Free external resources used by this algorithm.
void sgs.controller.simulation.AbstractDistributionAlgorithm.closeLog()
Try to make a new log-Stream Close log-Stream, if it exists.
References sgs.controller.simulation.AbstractDistributionAlgorithm.log.
Referenced by sgs.controller.simulation.DCPowerFlowCalculator.initializeAlgorithm, sgs.controller.simulation.SimplePowerDistribution.unloadAlgorithm, sgs.controller.simulation.SimplePowerDistribution.simulationStopped.
void sgs.controller.simulation.AbstractDistributionAlgorithm.log(String s)
Log information if log-Stream exists. s
References sgs.controller.simulation.AbstractDistributionAlgorithm.log.
static void sgs.controller.simulation.AbstractDistributionAlgorithm.setDefaultPropertiesForBusAndPath(SgsGridModel gridModel)
References sgs.model.variables.EnumPV.resistance, sgs.model.variables.EnumPV.transportPowerDecrement, sgs.model.variables.EnumPV.powerLineCharge, sgs.model.variables.EnumPV.powerConsumption, sgs.model.variables.EnumPV.powerProduction, sgs.model.variables.EnumPV.powerDemand, sgs.model.variables.EnumPV.maxPowerTransport.