sgs::controller::fileManagement::csvConstruction::CollectionsTreeTab
final SgsGridModel sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.gridModel
TreeView<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.collectionTreeView
Tab sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.resultsTab
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.objectTreeItem
final CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.collectionRoot
StringBuilder sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.header
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.savedTree
List<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.choosenPath
CheckBoxActionListener sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.cbActionListener
sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.CollectionsTreeTab(SgsGridModel gridModel)
constructor gridController gridModel
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.createObject(SmartGridObject sgo)
called by GiveDataCollection, to create the objectPart of its Tree. first it creates the CheckBoxTreeItem for the transfered Object -> callcreateObjectNode(SmartGridObjectsgo) second it adds the transfered SmartGridObject to the methodcreateTrueListArray() sgo - transfered SmartGridObject objectTreeItem - for the specific transfered SmartGridObject sgo
List<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getChoosenPathList()
choosenPath
Tab sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getChoosenTab()
Referenced by sgs.controller.fileManagement.csvConstruction.CSVController.getChoosenTabPane.
StringBuilder sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getHeader()
header
Referenced by sgs.controller.fileManagement.csvConstruction.CSVController.run.
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getobjectTreeItem()
objectTreeItem
Tab sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getResultsTab()
resultsTab
Referenced by sgs.controller.fileManagement.csvConstruction.CSVController.getChoiceTabPane.
void sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.start(Stage arg0)
void sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.setObjectTreeItem(CheckBoxTreeItem< String > newObjectTree)
newObjectTree
void sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.createChoosenPath()
creates the choosenPath , it helps to create the header and to organise the data
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getBusTree()
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.getPathTree()
The Collection Node has two children. One is the BusTree, and the other is the PathTree. Careful: Algorithm tells if we haven an path or not. so if the algorithm don't need paths, there's only an empty path tree. pathTree - check all paths on the grid. each object that is not a Super Conductor/Connector should be in the tree.
void sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.makeEventListener(final CheckBoxTreeItem< String > node)
add a listener to every node in the CheckboxTree. this listener check from the clicked node, is it a leaf, is it the last parent? create a sub tree, and add it to the existend TreeItem in choosenObjectTree, node
void sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.recAllLeafes(List< TreeItem< String >> nodes, TreeItem< String > isSelectedNode)
nodes isSelectedNode
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CollectionsTreeTab.trueParam(SmartGridObject sgo)
sgo trueListObjectNode - a Node with node and leave