sgs::model::simulation::Path
Bus sgs.model.simulation.Path.bus1
Bus sgs.model.simulation.Path.bus2
VariableSet sgs.model.simulation.Path.tmpVariableSet
LinkedList<SmartGridObject> sgs.model.simulation.Path.pathObjects
Referenced by sgs.model.simulation.Path.Path, sgs.model.simulation.Path.refreshValues, sgs.model.simulation.Path.copy.
VariableCollection sgs.model.simulation.Path.variableCollection
Referenced by sgs.model.simulation.Path.Path, sgs.model.simulation.Path.copy.
LinkedList<SmartGridObject> sgs.model.simulation.Path.notVisitedTmp
Referenced by sgs.model.simulation.Path.copy.
sgs.model.simulation.Path.Path(Bus busA, Bus busB, LinkedList< SmartGridObject > pathObjects, VariableCollection variableCollection)
Constructor: Full, TODO: VariableCollection busA - not null busB - not null pathObjects variableCollection
References sgs.model.simulation.Path.pathObjects, sgs.model.simulation.Path.variableCollection.
Referenced by sgs.model.simulation.Path.copy.
sgs.model.simulation.Path.Path(VariableCollection variableCollection)
Constructor: Empty
References sgs.model.simulation.Path.variableCollection.
void sgs.model.simulation.Path.setBuses(Bus busA, Bus busB)
Stores sorted buses. Must not be null. busA busB
References sgs.model.simulation.Bus.getNumber.
Referenced by sgs.model.simulation.Path.addBus.
int sgs.model.simulation.Path.getNrOfBuses()
Referenced by sgs.model.simulation.Path.addBus.
boolean sgs.model.simulation.Path.addBus(Bus busX)
Add up to two buses, further buses ignored busX true if added
References sgs.model.simulation.Path.getNrOfBuses, sgs.model.simulation.Path.setBuses.
Bus sgs.model.simulation.Path.getBus1()
the firstBus
Referenced by sgs.model.simulation.Path.toString.
Bus sgs.model.simulation.Path.getBus2()
the secondBus
Referenced by sgs.model.simulation.Path.toString.
VariableSet sgs.model.simulation.Path.getVariableSet()
the VariableSet owned by this object; or null (no owned variable set)
NumericValue sgs.model.simulation.Path.getValue(EnumPV variableName)
variableName value for variableName, or null if name is not found.
void sgs.model.simulation.Path.refreshValues()
Collects current simulation values with variableCollector
References sgs.model.simulation.Path.pathObjects.
Path sgs.model.simulation.Path.copy()
a copy of this path. Depth: Lists/Collections are copied.
References sgs.model.simulation.Path.Path, sgs.model.simulation.Path.pathObjects, sgs.model.simulation.Path.variableCollection, sgs.model.variables.collector.VariableCollection.copy, sgs.model.simulation.Path.notVisitedTmp.
String sgs.model.simulation.Path.toString()
References sgs.model.simulation.Path.getBus1, sgs.model.simulation.Path.getBus2.