sgs::model::variables::NumericValue
double sgs.model.variables.NumericValue.real
real and imaginary part of value
double sgs.model.variables.NumericValue.imaginary
boolean sgs.model.variables.NumericValue.isReal
True if using only real value
sgs.model.variables.NumericValue.NumericValue()
References sgs.model.variables.NumericValue.setValue.
Referenced by sgs.model.variables.NumericValue.copy, sgs.model.variables.NumericValue.main2.
sgs.model.variables.NumericValue.NumericValue(double real)
References sgs.model.variables.NumericValue.setValue.
sgs.model.variables.NumericValue.NumericValue(double real, double imaginary)
References sgs.model.variables.NumericValue.setValue.
sgs.model.variables.NumericValue.NumericValue(Complex c)
References sgs.model.variables.NumericValue.setValue.
sgs.model.variables.NumericValue.NumericValue(NumericValue n)
References sgs.model.variables.NumericValue.setValue.
sgs.model.variables.NumericValue.NumericValue(String complexValue)
Constructor with String value. Stores object value, not String. Watch out for parsing exceptions. Accepted formats: 100,200 -> 100 + 200i 100 200 -> 100 + 200i 100 -> 100 + 200i 100,,,200 -> 100 + 200i Combinations with whitespaces at start, end and middle ,200 -> 0 + 200i 200 -> 200 + 0i 100 -> 100 + 0i value
References sgs.model.variables.NumericValue.setValue.
void sgs.model.variables.NumericValue.setValue(double real)
d - a double value. May not be fully compatible with every value class.
Referenced by sgs.model.variables.NumericValue.NumericValue, sgs.model.variables.NumericValue.setValue.
void sgs.model.variables.NumericValue.setValue(Complex c)
complex - a Complex value. May not be fully compatible with every value class.
References sgs.model.variables.NumericValue.setValue.
void sgs.model.variables.NumericValue.setValue(NumericValue v)
numericValue - {real,imaginary}. May not be fully compatible with every value class.
References sgs.model.variables.NumericValue.setValue.
void sgs.model.variables.NumericValue.setValue(String complex)
value - a String representation of the specific value class. Should be parsable.
References sgs.model.variables.NumericValue.r, sgs.model.variables.NumericValue.i, sgs.model.variables.NumericValue.setValue.
void sgs.model.variables.NumericValue.setValue(double real, double imaginary)
void sgs.model.variables.NumericValue.setReal(double real)
void sgs.model.variables.NumericValue.setImaginary(double imaginary)
double sgs.model.variables.NumericValue.r()
Real part of value
Referenced by sgs.model.variables.NumericValue.setValue.
double sgs.model.variables.NumericValue.getReal()
Referenced by sgs.model.simulation.Bus.getBusVoltage.
double sgs.model.variables.NumericValue.i()
imaginary part of value
Referenced by sgs.model.variables.NumericValue.setValue.
double sgs.model.variables.NumericValue.getImaginary()
Referenced by sgs.model.gridObjects.SmartGridObject.setCurrentVoltage, sgs.model.simulation.Bus.getBusVoltage, sgs.model.variables.NumericValue.add, sgs.model.variables.NumericValue.subtract, sgs.model.variables.NumericValue.multiply, sgs.model.variables.NumericValue.divide, sgs.model.variables.StringValue.setValue.
double sgs.model.variables.NumericValue.abs()
sqrt(a^2+b^2)
References sgs.model.variables.NumericValue.isReal.
Referenced by sgs.controller.simulation.calculation.GaussSeidelPFSolver.solve, sgs.model.simulation.Bus.setBusVoltage.
boolean sgs.model.variables.NumericValue.isReal()
true if it has real value only
Referenced by sgs.model.variables.NumericValue.abs, sgs.model.variables.NumericValue.getValue, sgs.model.variables.NumericValue.getValueDouble, sgs.model.variables.NumericValue.divide, sgs.model.variables.NumericValue.toString.
boolean sgs.model.variables.NumericValue.isNaN()
true if real part and imaginary part are NaN
String sgs.model.variables.NumericValue.getValue()
value - a object the specific value class. Should be of correct type. a string representation of the value
References sgs.model.variables.NumericValue.isReal.
NumericValue sgs.model.variables.NumericValue.getValueNumeric()
a value object, handle with care a NumericValue object or null
double sgs.model.variables.NumericValue.getValueDouble()
the absolute value from the complex object
References sgs.model.variables.NumericValue.isReal.
Complex sgs.model.variables.NumericValue.getValueComplex()
a complex representation of the value, zero for non numeric values
NumericValue sgs.model.variables.NumericValue.add(NumericValue val)
Add another NumericValue to this value. val
References sgs.model.variables.NumericValue.getImaginary.
NumericValue sgs.model.variables.NumericValue.subtract(NumericValue val)
Subtract another NumericValue from this value. val this
References sgs.model.variables.NumericValue.getImaginary.
NumericValue sgs.model.variables.NumericValue.multiply(NumericValue val)
Multiply by another NumericValue. val
References sgs.model.variables.NumericValue.getImaginary.
NumericValue sgs.model.variables.NumericValue.divide(NumericValue val)
Divide by another NumericValue. val
References sgs.model.variables.NumericValue.getImaginary, sgs.model.variables.NumericValue.isReal.
NumericValue sgs.model.variables.NumericValue.conjugate()
Sets the imaginary part minus imaginary part.
NumericValue sgs.model.variables.NumericValue.copy()
a Copy up to primitive variables from this Value.
References sgs.model.variables.NumericValue.NumericValue.
Referenced by sgs.controller.simulation.calculation.GaussSeidelPFSolver.solve.
String sgs.model.variables.NumericValue.toString()
References sgs.model.variables.NumericValue.isReal.
NumericValue sgs.model.variables.NumericValue.roundValue(int roundPower)
static String [] sgs.model.variables.NumericValue.numberSplit(String s, char sep)
Get up to two numbers separated by sep. s - trimmed string with numbers sep - separator String array of size 0, 1 or 2 with (hopefully correct) numbers. Number format is not tested. Whitespace characters are removed.
static void sgs.model.variables.NumericValue.main2(String[] args)
Testing
References sgs.model.variables.NumericValue.NumericValue.