sgs::controller::undoableEdit::UndoRedoManager
final GridController sgs.controller.undoableEdit.UndoRedoManager.gridController
SmartGridObject sgs.controller.undoableEdit.UndoRedoManager.sgo
boolean sgs.controller.undoableEdit.UndoRedoManager.canRedo
boolean sgs.controller.undoableEdit.UndoRedoManager.objectDeleted
boolean sgs.controller.undoableEdit.UndoRedoManager.canUndo
sgs.controller.undoableEdit.UndoRedoManager.UndoRedoManager(GridController gc, SmartGridObject sgs, boolean objectStatus)
Constructor for undoing an delete action in the GridMap gc sgs
boolean sgs.controller.undoableEdit.UndoRedoManager.addEdit(UndoableEdit arg0)
boolean sgs.controller.undoableEdit.UndoRedoManager.canRedo()
Referenced by sgs.controller.undoableEdit.UndoRedoManager.die.
boolean sgs.controller.undoableEdit.UndoRedoManager.canUndo()
Referenced by sgs.controller.undoableEdit.UndoRedoManager.die.
void sgs.controller.undoableEdit.UndoRedoManager.die()
References sgs.controller.undoableEdit.UndoRedoManager.canRedo, sgs.controller.undoableEdit.UndoRedoManager.canUndo.
String sgs.controller.undoableEdit.UndoRedoManager.getPresentationName()
Referenced by sgs.controller.undoableEdit.UndoRedoManager.getRedoPresentationName, sgs.controller.undoableEdit.UndoRedoManager.getUndoPresentationName.
String sgs.controller.undoableEdit.UndoRedoManager.getRedoPresentationName()
References sgs.controller.undoableEdit.UndoRedoManager.getPresentationName.
String sgs.controller.undoableEdit.UndoRedoManager.getUndoPresentationName()
References sgs.controller.undoableEdit.UndoRedoManager.getPresentationName.
boolean sgs.controller.undoableEdit.UndoRedoManager.isSignificant()
void sgs.controller.undoableEdit.UndoRedoManager.redo()
boolean sgs.controller.undoableEdit.UndoRedoManager.replaceEdit(UndoableEdit arg0)
void sgs.controller.undoableEdit.UndoRedoManager.undo()