sgs::model::variables::VariableSet
final long sgs.model.variables.VariableSet.serialVersionUID
LinkedList<String> sgs.model.variables.VariableSet.modified
sgs.model.variables.VariableSet.VariableSet()
Constructor: Empty
Referenced by sgs.model.variables.VariableSet.combine, sgs.model.variables.VariableSet.copyKeepProperties, sgs.model.variables.VariableSet.makeDefaultVariableSet, sgs.model.variables.VariableSet.getVisibles.
boolean sgs.model.variables.VariableSet.add(SingleVariable a)
Does not allow overwriting names! true. SecurityException if you try to overwrite a name.
Referenced by sgs.model.gridObjects.SmartGridObject.getData, sgs.model.variables.VariableSet.getVisibles.
SingleVariable sgs.model.variables.VariableSet.add(EnumPV name)
Factory method currentpowerconsumption d the SingleVariable
boolean sgs.model.variables.VariableSet.addIfNotContained(SingleVariable a)
a see add() true if name was not contained (added)
boolean sgs.model.variables.VariableSet.addAllIfNotContained(VariableSet a)
a see add() true if name was not contained (added)
boolean sgs.model.variables.VariableSet.remove(Object o)
boolean sgs.model.variables.VariableSet.remove(EnumPV name)
Remove attribute with name. name true if success
boolean sgs.model.variables.VariableSet.remove(String name)
remove(PredefinedVariablesEnum)
boolean sgs.model.variables.VariableSet.remove(SingleVariable a)
remove(PredefinedVariablesEnum)
SingleVariable sgs.model.variables.VariableSet.get(EnumPV name)
name attribute with 'name' or null.
SingleVariable sgs.model.variables.VariableSet.get(int row)
boolean sgs.model.variables.VariableSet.contains(String name)
contains(PredefinedVariablesEnum)
References sgs.model.variables.VariableSet.contains.
boolean sgs.model.variables.VariableSet.contains(SingleVariable a)
contains(PredefinedVariablesEnum)
String sgs.model.variables.VariableSet.toString()
String sgs.model.variables.VariableSet.toStringFull()
full content of set.
Object [][] sgs.model.variables.VariableSet.getObjectArray()
Object array with dimensions [size][2] where array[i][0] = name array[i][1] = value
void sgs.model.variables.VariableSet.set(String name, String value)
Set an EXISTING variable with name 'name'. name value
void sgs.model.variables.VariableSet.set(EnumPV name, Object value)
Set an EXISTING variable with name 'name'. name value
boolean sgs.model.variables.VariableSet.isUsed(EnumPV name)
sv true if Variable exists AND isVisible OR isEditable (definition)
References sgs.model.variables.SingleVariable.properties.
Referenced by sgs.controller.simulation.SimplePowerDistribution.calculationStep.
VariableSet sgs.model.variables.VariableSet.copyKeepProperties()
a Copy up to value from this Set.
References sgs.model.variables.VariableSet.VariableSet.
VariableSet sgs.model.variables.VariableSet.getVisibles()
a variable set containing only the visible ones.
References sgs.model.variables.VariableSet.VariableSet, sgs.model.variables.SingleVariable.properties, sgs.model.variables.VariableSet.add.
SingleVariable sgs.model.variables.VariableSet.get(String name)
get(PredefinedVariablesEnum)
References sgs.model.variables.SingleVariable.compareTo.
boolean sgs.model.variables.VariableSet.contains(EnumPV name)
name true if name is contained in set
Referenced by sgs.model.variables.VariableSet.contains.
static VariableSet sgs.model.variables.VariableSet.combine(VariableSet a, VariableSet b)
Get combined variable set. Makes no deep copy! a b new set with variables from a and b. Prefers variables in b.
References sgs.model.variables.VariableSet.VariableSet.
static VariableSet sgs.model.variables.VariableSet.makeDefaultVariableSet()
a variableSet with all possible variables
References sgs.model.variables.VariableSet.VariableSet.