sgs::controller::ReflectionStuff
boolean sgs.controller.ReflectionStuff.useSubPackages
Flag defining if packages below the (parameter) package should be used at related functions
Referenced by sgs.controller.ReflectionStuff.getClassesForPackage.
static void sgs.controller.ReflectionStuff.mainTest(String[] args)
Testing args FileNotFoundException
References sgs.controller.ReflectionStuff.getClassesForPackage, sgs.controller.ReflectionStuff.getSubClasses.
static ArrayList<Class<?> > sgs.controller.ReflectionStuff.getSubClasses(Class<?> topClass, ArrayList< Class<?>> classes, boolean canBeAbstract)
Returns a list of sub-classes from the defined list of classes. topClass classes sub-classes of topClass, excluding topClass, excluding abstract classes getClassesForPackage(String pkgName)
Referenced by sgs.controller.ReflectionStuff.mainTest.
static ArrayList<Class<?> > sgs.controller.ReflectionStuff.getClassesForPackage(Class<?> topClass)
topClass all classes in the same package. getClassesForPackage(String pkgName)
Referenced by sgs.controller.ReflectionStuff.mainTest, sgs.controller.ReflectionStuff.getClassesForPackage.
static ArrayList<Class<?> > sgs.controller.ReflectionStuff.getClassesForPackage(Package pkg)
getClassesForPackage(String pkgName)
References sgs.controller.ReflectionStuff.getClassesForPackage.
static ArrayList<Class<?> > sgs.controller.ReflectionStuff.getClassesForPackage(String pkgName)
Original from Dave Dopson, https://github.com/ddopson/java-class-enumerator pkgName - e.g. "sgs.controller.interfaces" all classes in the package.
References sgs.controller.ReflectionStuff.useSubPackages, sgs.controller.ReflectionStuff.getClassesForPackage.