sgs::model::variables::VariableProperties
final VariableProperties sgs.model.variables.VariableProperties.DefaultProperties
Referenced by sgs.model.variables.VariableProperties.set.
boolean sgs.model.variables.VariableProperties.isVisible
true if variable should be visible for the user
boolean sgs.model.variables.VariableProperties.isEditable
true if variable should be editable for the user, or true if not visible and variable is used internally
boolean sgs.model.variables.VariableProperties.isSet
true if properties were set
Referenced by sgs.model.variables.VariableProperties.set, sgs.model.variables.VariableProperties.reset.
sgs.model.variables.VariableProperties.VariableProperties()
sgs.model.variables.VariableProperties.VariableProperties(boolean isVisible, boolean isEditable)
Use false/true if variable is used internally, but not by the user. isVisible isEditable
References sgs.model.variables.VariableProperties.isVisible, sgs.model.variables.VariableProperties.isEditable.
boolean sgs.model.variables.VariableProperties.isVisible()
true if variable should be visible to user
Referenced by sgs.model.variables.VariableProperties.VariableProperties, sgs.model.variables.VariableProperties.set, sgs.model.variables.VariableProperties.reset.
boolean sgs.model.variables.VariableProperties.isEditable()
true if variable should be editable by user
Referenced by sgs.model.variables.VariableProperties.VariableProperties, sgs.model.variables.VariableProperties.set, sgs.model.variables.VariableProperties.reset.
void sgs.model.variables.VariableProperties.set(boolean visible, boolean editable)
b
References sgs.model.variables.VariableProperties.DefaultProperties, sgs.model.variables.VariableProperties.isVisible, sgs.model.variables.VariableProperties.isEditable, sgs.model.variables.VariableProperties.isSet.
void sgs.model.variables.VariableProperties.reset()
References sgs.model.variables.VariableProperties.isVisible, sgs.model.variables.VariableProperties.isEditable, sgs.model.variables.VariableProperties.isSet.