sgs::model::gridObjects::SmartGridObject
VariableSet sgs.model.gridObjects.SmartGridObject.variableSet
Referenced by sgs.controller.simulation.SimplePowerDistribution.calculationStep, sgs.model.gridObjects.SmartGridObject.SmartGridObject, sgs.model.gridObjects.SmartGridObject.getData, sgs.model.gridObjects.SmartGridObject.getVariableSet.
OverlayList sgs.model.gridObjects.SmartGridObject.overlays
LinkedList<Window> sgs.model.gridObjects.SmartGridObject.ownedWindows
Holds windows owned inly by this specific object
Referenced by sgs.controller.GridController.refreshAllObjectParameterWindows, sgs.model.gridObjects.SmartGridObject.closeAllWindows.
GridDataNode sgs.model.gridObjects.SmartGridObject.selectedNode
Referenced by sgs.model.gridObjects.SmartGridObject.setProperties.
AbstractModel sgs.model.gridObjects.SmartGridObject.model
Referenced by sgs.model.gridObjects.Consumer.setModel, sgs.model.gridObjects.PowerPlant.getModel, sgs.model.gridObjects.PowerPlant.setModel, sgs.model.gridObjects.SmartGridObject.getModel, sgs.model.gridObjects.SmartGridObject.setModel.
String sgs.model.gridObjects.SmartGridObject.objectName
boolean sgs.model.gridObjects.SmartGridObject.draggable
true if this object can be dragged in the grid
Referenced by sgs.model.gridObjects.SmartGridObject.isDraggable, sgs.model.gridObjects.SmartGridObject.setDraggable.
int sgs.model.gridObjects.SmartGridObject.busNumber
Simulation relevant parameter
SgsGridModel sgs.model.gridObjects.SmartGridObject.gridModel
Model is static, so it doesn't need to be set for every object extra
sgs.model.gridObjects.SmartGridObject.SmartGridObject()
New Constructor for variable set. SmartGridObject adds all default values
References sgs.model.gridObjects.SmartGridObject.variableSet.
int sgs.model.gridObjects.SmartGridObject.getBusNumber()
the busNumber
void sgs.model.gridObjects.SmartGridObject.setBusNumber(int busNumber)
busNumber the clusterNumber to set
Bus sgs.model.gridObjects.SmartGridObject.getBus()
the Bus corresponding to the busNumber. May result in an Error if data is not up to date.
AbstractModel sgs.model.gridObjects.SmartGridObject.getModel()
the current model
References sgs.model.gridObjects.SmartGridObject.model.
void sgs.model.gridObjects.SmartGridObject.setModel(AbstractModel model)
References sgs.model.gridObjects.SmartGridObject.model.
NumericValue sgs.model.gridObjects.SmartGridObject.getCurrentPowerConsumption()
current power consumption of this object
References sgs.model.variables.EnumPV.powerConsumption.
void sgs.model.gridObjects.SmartGridObject.setCurrentPowerConsumption(NumericValue numeric)
numeric - the new charge value for this element
References sgs.model.variables.EnumPV.powerConsumption.
Referenced by sgs.model.gridObjects.SmartGridObject.setCurrentPowerConsumption.
void sgs.model.gridObjects.SmartGridObject.setCurrentPowerConsumption(double value)
References sgs.model.gridObjects.SmartGridObject.setCurrentPowerConsumption.
void sgs.model.gridObjects.SmartGridObject.resetCurrentPowerConsumption()
Resets current power consumption
References sgs.model.variables.EnumPV.powerProduction, sgs.model.variables.EnumPV.powerConsumption.
NumericValue sgs.model.gridObjects.SmartGridObject.getPowerProduction()
power production of this object
References sgs.model.variables.EnumPV.powerProduction.
void sgs.model.gridObjects.SmartGridObject.setPowerProduction(double powerProduction)
Producer method powerProduction
References sgs.model.variables.EnumPV.powerProduction.
void sgs.model.gridObjects.SmartGridObject.setPowerProduction(NumericValue powerProduction)
Producer method powerProduction
References sgs.model.variables.EnumPV.powerProduction.
void sgs.model.gridObjects.SmartGridObject.setPeakPower(NumericValue ratedPower)
Producer method ratedPower
References sgs.model.variables.EnumPV.powerProductionOptimal.
void sgs.model.gridObjects.SmartGridObject.setPeakPower(double ratedPower)
Producer method powerProduction
References sgs.model.variables.EnumPV.powerProductionOptimal.
NumericValue sgs.model.gridObjects.SmartGridObject.getPeakPower()
Producer method
References sgs.model.variables.EnumPV.powerProductionOptimal.
NumericValue sgs.model.gridObjects.SmartGridObject.getPowerDemand()
power usage of this object
References sgs.model.variables.EnumPV.powerDemand.
double sgs.model.gridObjects.SmartGridObject.getMaxPowerTransport()
maximum energy this object can "transport" (?)
References sgs.model.variables.EnumPV.maxPowerTransport.
double sgs.model.gridObjects.SmartGridObject.getTransportPowerDecrement()
Energy decrement factor e.g. 0.01 = 1 percent energy decrement
References sgs.model.variables.EnumPV.transportPowerDecrement.
void sgs.model.gridObjects.SmartGridObject.setResistance(NumericValue resistance)
References sgs.model.variables.EnumPV.resistance.
Referenced by sgs.model.gridObjects.Connector.Connector, sgs.model.gridObjects.PowerLine.PowerLine.
NumericValue sgs.model.gridObjects.SmartGridObject.getResistance()
References sgs.model.variables.EnumPV.resistance.
NumericValue sgs.model.gridObjects.SmartGridObject.getCurrentVoltage()
References sgs.model.variables.EnumPV.currentVoltage.
void sgs.model.gridObjects.SmartGridObject.setCurrentVoltage(double currentVoltage)
References sgs.model.variables.EnumPV.currentVoltage.
void sgs.model.gridObjects.SmartGridObject.setCurrentVoltage(NumericValue currentVoltage)
Set current voltage and calculated angle. currentVoltage
References sgs.model.variables.NumericValue.getImaginary, sgs.model.variables.EnumPV.voltageAngle, sgs.model.variables.EnumPV.currentVoltage.
void sgs.model.gridObjects.SmartGridObject.setPowerLineCharge(NumericValue powerLineCharge)
References sgs.model.variables.EnumPV.powerLineCharge.
Referenced by sgs.model.gridObjects.PowerLine.PowerLine.
double sgs.model.gridObjects.SmartGridObject.getLineCharge()
References sgs.model.variables.EnumPV.powerLineCharge.
void sgs.model.gridObjects.SmartGridObject.updateObject(GregorianCalendar currentTime, Weather weather, int simulationResolutionMinutes)
References sgs.model.gridObjects.SmartGridObject.getEnum.
abstract void sgs.model.gridObjects.SmartGridObject.setProductionToWeatherAndTime(GregorianCalendar currentTime, Weather weather)
Adjusts energy production to specific weather and time. Depends on EnumPV.powerProductionOptimal weather
VariableSet sgs.model.gridObjects.SmartGridObject.getData()
VariableSet of this object Deprecateduse the getVisibles() method of the VariableSet.class
References sgs.model.gridObjects.SmartGridObject.variableSet, sgs.model.variables.VariableSet.add.
boolean sgs.model.gridObjects.SmartGridObject.addWindow(Window w)
Adds a window w which is owned exclusively by this object. The window should be closed if this object stops to exist or will not be used any more. w like in LinkedList#add removeWindow() closeAllWindows()
boolean sgs.model.gridObjects.SmartGridObject.removeWindow(Window w)
Remove a window w which was owned exclusively by this object. Should also call w.dispose(). w like in LinkedList#remove #removeAllWindows() #add(Window)
Referenced by sgs.model.gridObjects.SmartGridObject.closeAllWindows.
int sgs.model.gridObjects.SmartGridObject.closeAllWindows()
Will close all windows owned exclusively by this object. Close is executed by calling Window.dispose()}number of windows. #add(Window)
References sgs.model.gridObjects.SmartGridObject.ownedWindows, sgs.model.gridObjects.SmartGridObject.removeWindow.
boolean sgs.model.gridObjects.SmartGridObject.isDraggable()
References sgs.model.gridObjects.SmartGridObject.draggable.
void sgs.model.gridObjects.SmartGridObject.setDraggable(boolean draggable)
References sgs.model.gridObjects.SmartGridObject.draggable.
VariableSet sgs.model.gridObjects.SmartGridObject.getVariableSet()
the VariableSet owned by this object; or null (no owned variable set)
References sgs.model.gridObjects.SmartGridObject.variableSet.
abstract GridDataEnum sgs.model.gridObjects.SmartGridObject.getEnum()
corresponding enum for this object.
Referenced by sgs.controller.GridController.actionfor_pasteCopiedObject, sgs.model.gridObjects.SmartGridObject.updateObject, sgs.view.PropertiesDialog.PropertiesDialog.
String sgs.model.gridObjects.SmartGridObject.toString()
String sgs.model.gridObjects.SmartGridObject.getObjectName()
String sgs.model.gridObjects.SmartGridObject.getParameterOfSGO()
To avoid initializing VariableSet and SingleVariable in the CSV Class GiveDataObject and GiveDataParam, only return visible parameters in a string for the TreeNodes sgoParameter
NumericValue sgs.model.gridObjects.SmartGridObject.getBusVoltage()
void sgs.model.gridObjects.SmartGridObject.setProperties(boolean visible, boolean editable, EnumPV...variables)
References sgs.model.gridObjects.SmartGridObject.selectedNode, sgs.model.gridData.GridDataNode.nodeVariableSet.
Double sgs.model.gridObjects.SmartGridObject.roundC(double value)
double sgs.model.gridObjects.SmartGridObject.rad2deg(double rad)
double sgs.model.gridObjects.SmartGridObject.deg2rad(double deg)
static SmartGridObject sgs.model.gridObjects.SmartGridObject.factory(GridDataEnum enu)
enu new grid data object for GridDataEnum. Mind to set coordinates if needed!
Referenced by sgs.controller.GridController.actionfor_pasteCopiedObject.