sgs::controller::ColorOverlayController
ColorLegendPanel sgs.controller.ColorOverlayController.legendPanel
final GridController sgs.controller.ColorOverlayController.gridController
final SgsGridModel sgs.controller.ColorOverlayController.gridModel
final PrimaryViewI sgs.controller.ColorOverlayController.view
final ColorLegendPanel sgs.controller.ColorOverlayController.eastColorPanel
BufferedImage sgs.controller.ColorOverlayController.img
final boolean [] sgs.controller.ColorOverlayController.overlayNumberArray
sgs.controller.ColorOverlayController.ColorOverlayController(GridController gridController2, PrimaryViewI view)
constructor gridController2 view
void sgs.controller.ColorOverlayController.init(int legendNumber)
called from MenuController.java Initialize the colorOvelay, the legend and the overlay on the grid legendNumber
References sgs.controller.ColorOverlayController.repaint.
Referenced by sgs.controller.ColorOverlayController.initAll.
boolean sgs.controller.ColorOverlayController.checkOverlayUse()
check if a legend is activated if yes, set the overlayUse to booelan value true, else to false
Referenced by sgs.controller.ColorOverlayController.repaint.
void sgs.controller.ColorOverlayController.mark(int orgX, int orgY, int[][][] gridData3D)
Referenced by sgs.controller.ColorOverlayController.markAll, sgs.controller.ColorOverlayController.markOne.
void sgs.controller.ColorOverlayController.markAll()
method marks every single grid tile
References sgs.controller.ColorOverlayController.mark.
void sgs.controller.ColorOverlayController.markOne(int orgX, int orgY, boolean markMore)
we mark the clicked spot with a transparent overlay markMore - boolean to check if more objects should be marked. Method still mark only one object at the time, but dont delete the other marks x - x coordination of object y - y coordination of object
References sgs.controller.ColorOverlayController.mark.
void sgs.controller.ColorOverlayController.repaint()
repaints the grid, and the legends
References sgs.controller.ColorOverlayController.checkOverlayUse, sgs.model.SgsGridModel.gridObjectList, sgs.model.SgsGridModel.overlayMode, sgs.model.SgsGridModel.gridData3D.
Referenced by sgs.controller.ColorOverlayController.init, sgs.controller.ColorOverlayController.repaintData.
void sgs.controller.ColorOverlayController.repaintData()
this methode was called from other classes, to repaint the grid. they dont know which overlay is actually in use, so they also dont know the number which is needed in the repaint() methode.
References sgs.controller.ColorOverlayController.repaint.
boolean [] sgs.controller.ColorOverlayController.getOverlayNumberArray()
we save all checked overlay an array of the overlays by number
void sgs.controller.ColorOverlayController.initAll()
this method inis all legends and their overlays.
References sgs.controller.ColorOverlayController.init.
void sgs.controller.ColorOverlayController.addOverlay(int x, int y, int z, Color color, int overlayIndex, int[][][] gridData3D)
Add Overlay color to jGridMap and ID to gridData x x coordinate of object y y coordinate of object z size of tile color calculated color overlayIndex unused gridData3D
Color sgs.controller.ColorOverlayController.colorOverlay2(SmartGridObject sgo)
calculate new value for result. if result is greater than 1, retun 1, or if result is smaller than zero, return zero. if we are not doing that, the formula will calculate us another color, which is not black, white, or gray shaded. sgo - which object is it the voltageAngle value for the given sgo object
Color sgs.controller.ColorOverlayController.colorOverlay3(SmartGridObject sgo)
void sgs.controller.ColorOverlayController.resetOverlayData(int[][][] gridData3D)
Reset overlay data in grid. (z>1) gridData3D
int sgs.controller.ColorOverlayController.setOverlay(int[][][] gridData3D, SmartGridObject sgo, OverlayMode overlayMode, int overlayIndex)
gridData3D - data for objects and overlays (z>0) sgo - object for overlays overlayIndex - current overlayIndex (unused) new overlayIndex (unused)
Color sgs.controller.ColorOverlayController.getClassicOverlayColor(SmartGridObject sgo)
Classical consumption and production in red/green overlayData