sgs::controller::simulation::TimeThread
AbstractDistributionAlgorithm sgs.controller.simulation.TimeThread.algorithm
The used algorithm, abstract class
final GridController sgs.controller.simulation.TimeThread.gridController
The grid controller for interaction/control
final ButtonController sgs.controller.simulation.TimeThread.buttonController
The button controller for interaction/control
final SgsGridModel sgs.controller.simulation.TimeThread.gridModel
the model
boolean sgs.controller.simulation.TimeThread.doRun
true while TimeThread should run
final int sgs.controller.simulation.TimeThread.weatherChangeLimit
weather changes at least once every X minutes, but may be the same weather.
boolean sgs.controller.simulation.TimeThread.isRunning
true while TimeThread is running
boolean sgs.controller.simulation.TimeThread.realTime
true -> run simulation slowly for user
Referenced by sgs.controller.ButtonController.actionFor_bStartStopSim, sgs.controller.simulation.TimeThread.startOrStop, sgs.controller.simulation.TimeThread.run.
GregorianCalendar sgs.controller.simulation.TimeThread.startTime
simulation start
GregorianCalendar sgs.controller.simulation.TimeThread.currentTime
simulation current time
Referenced by sgs.controller.simulation.TimeThread.TimeThread, sgs.controller.simulation.TimeThread.run.
GregorianCalendar sgs.controller.simulation.TimeThread.endTime
simulation planned end
Referenced by sgs.controller.simulation.TimeThread.run.
int sgs.controller.simulation.TimeThread.simulationResolutionMinutes
simulated time between two simulation steps in minutes, e.g. 1 hour = 60
Referenced by sgs.controller.simulation.TimeThread.run.
int sgs.controller.simulation.TimeThread.interSimStepMiliSec
Realtime between two simulationsteps
Referenced by sgs.controller.simulation.TimeThread.run.
Weather sgs.controller.simulation.TimeThread.currentWeather
Referenced by sgs.controller.simulation.TimeThread.TimeThread, sgs.controller.simulation.TimeThread.run.
final CSVController sgs.controller.simulation.TimeThread.csvController
SpeedChanger sgs.controller.simulation.TimeThread.sliderDialog
Referenced by sgs.controller.simulation.TimeThread.startOrStop.
sgs.controller.simulation.TimeThread.TimeThread(GridController gridController, ButtonController buttonController, CSVController csvController)
Initialize and start time thread. Sets reference in GridModel gridController buttonController csvController
References sgs.controller.simulation.TimeThread.currentTime, sgs.controller.simulation.TimeThread.currentWeather.
synchronized void sgs.controller.simulation.TimeThread.startOrStop(boolean start)
Start or stop time thread. start
References sgs.controller.simulation.TimeThread.isRunning, sgs.controller.simulation.TimeThread.realTime, sgs.controller.simulation.TimeThread.sliderDialog.
Referenced by sgs.controller.simulation.TimeThread.run.
AbstractDistributionAlgorithm sgs.controller.simulation.TimeThread.getAlgorithm()
the currently used algorithm.
synchronized void sgs.controller.simulation.TimeThread.changeAlgorithm(AbstractDistributionAlgorithm newAlgorithm)
Change the used algorithm. does not stop running simulationsinitializes the algorithm. newAlgorithm
void sgs.controller.simulation.TimeThread.run()
IOException e if not possible FileChooserController.createCSVController
References sgs.controller.simulation.TimeThread.isRunning, sgs.controller.simulation.TimeThread.currentTime, sgs.controller.simulation.TimeThread.endTime, sgs.controller.simulation.TimeThread.realTime, sgs.controller.simulation.TimeThread.interSimStepMiliSec, sgs.controller.simulation.TimeThread.simulationResolutionMinutes, sgs.controller.simulation.TimeThread.currentWeather, sgs.controller.simulation.TimeThread.startOrStop.
boolean sgs.controller.simulation.TimeThread.isDoRun()
getter for boolean doRun doRun value
void sgs.controller.simulation.TimeThread.setDoRun(boolean doRun)
Setter for doRun Boolean doRun
static boolean sgs.controller.simulation.TimeThread.isRunning()
true if algorithm is currently still doing something or should start to do something.
Referenced by sgs.controller.simulation.TimeThread.startOrStop, sgs.controller.simulation.TimeThread.run.
static long sgs.controller.simulation.TimeThread.getSleepTimeMS(long interSimStepSec, long t0, long t1)
interSimStepMiliSec - time to sleep in seconds t0 - start, time before algorithm execution t1 - stop, time before sleep time left to sleep
void sgs.controller.simulation.TimeThread.simStep()
A single simulation step, locking Buses and Paths. Also sets production according to weather and time. Repaints View/Grid.
void sgs.controller.simulation.TimeThread.changeWeather()
Change 'currentWeather' randomly depending on 'weatherChangeLimit'
void sgs.controller.simulation.TimeThread.updateGridObjects(GregorianCalendar currentTime, Weather weather)
Set production of all SmartSimObjects to weather and time.