sgs::controller::fileManagement::csvConstruction::CheckBoxActionListener
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.haveData
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.savedChanges
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.dataChanged
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.choosenObjectTree
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.choosenCollectionTree
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.collectionTree
CheckBoxTreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.objectTree
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.foundInconsistency
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.siblingChangesAllNode
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.savedTree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.actionfor_cancelButton()
set the choosenCollectionTree back, to the old values, that are stored in the savedTree. set haveData back to false.
References sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setDataChanged.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.actionfor_saveButton()
actions for save Button set savedChanges to true set dataChanged to false set haveData to false
References sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setDataChanged.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.addNodeChoosenObjectTree(CheckBoxTreeItem< String > node)
add a TreeItem to the ChoosenObjectTree node
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.addNodeChoosenCollectionTree(CheckBoxTreeItem< String > node, TreeItem< String > list, TreeItem< String > node2)
add a node to a TreeItem given in the param list from Collections node - node from the CheckBoxTree that trows the ActionListener list - in which Tree (without CeckBoxes) we want to add a node node2 - a node(should be leaf) from the choosenCollectionTree
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recAllLeafes.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree(CheckBoxTreeItem< String >node)
list node one methode for adding and removing nodes from the choosenDataTrees. At first check if the node.getParent() is an all-node or a sgo-node. If it's an all-node, the node can only be in the objectTab, because only there are the nodes with the Titel "all .." . node - the node from the Tree that throws the actionlistener
References sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.addNodeChoosenCollectionTree, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.removeNodeChoosenCollectionTree, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.addNodeChoosenObjectTree, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.removeNodeChoosenObjectTree, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setDataChanged.
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.getFoundInconsistency()
foundInconsitency - boolean to tell if the user wanted to save data from an object, that he/she delayed later from the grid
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.getSavedObject()
choosenObjectTree
TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.getSavedCollection()
clear the choosenObjectTree call recAllLeafes function to search for the leaves in the choosenCollectionTree, and save them in the savedTreeCollection call recExpandTree function to expand each node of the tree choosenCollectionTree
References sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recAllLeafes.
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.isHaveData()
haveData - boolean to check if a notification to save the changes is needed
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.haveDataC()
this is a getter - Method for the Controller. in some possibilities the JavaFx has not initialized and would throw an exception
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.isSavedChanges()
savedChanges -
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recAllLeafes(TreeItem< String > list, TreeItem< String > choosenTree)
the recAllLeaves in the GiveDataCollections, put all leafs into a list, we want here to put it into a new tree. also if it found the leaf, it should check if the path even exists in the checkboxtree Collection and set the isSelected to true.
References sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.addNodeChoosenCollectionTree.
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.getSavedCollection.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.removeNodeChoosenObjectTree(CheckBoxTreeItem< String > node, CheckBoxTreeItem< String > objectTree)
remove nodes and the parents if necessary from the choosenObjectTree node - selected Node throws the action listener objectTree -
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.removeNodeChoosenCollectionTree(CheckBoxTreeItem< String > node, TreeItem< String > list, TreeItem< String > node2)
remove a node + parents if necessary from the choosenCollectionTree node
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setCollectionTree(CheckBoxTreeItem< String > collTree)
collTree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setObjectTree(CheckBoxTreeItem< String > objTree)
set the objTree into the objectTree, and so the actionListener to the address of the tree objTree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.setDataChanged(boolean b)
Referenced by sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.actionfor_cancelButton, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.actionfor_saveButton, sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.changeNodeInCheckBoxTree.
boolean sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.checkList(CheckBoxTreeItem< String > node)
the methode looks which Tree is the mother of the selected node, to avoid activating CheckBoxes and creating choosenTrees twice collectionTreeIsMother - is node a part of collectionTree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.checkSiblings(CheckBoxTreeItem< String > node)
this method checks if the siblings of a parent are also isSelected(true); if yes, then it will set the all-node also isSelected(true); other way around for isSelected(false) also node
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recSearchLeafeInCB(TreeItem< String > leaf, CheckBoxTreeItem< String > list)
when the user deleted one object, but has choosen paramaters from it, to save it during the simulation, its action creates an inconsistency we cant save anything, that isnt there anymore. the choosenTrees will always be new generated by each start of the frame. so we have to check if there are to many objects in the savedTree, than in the tree from the grid this function searchs rec for inconsistency leaf - from the savedTree list - the new generated choosenTree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recSearch(CheckBoxTreeItem< String > list, CheckBoxTreeItem< String > searchedNode, CheckBoxTreeItem< String > conditionNode)
recSearch search recursive for a spacific searchedNode in a transfered list (mostly the collectionTree or objectTree). Sometimes we want an extra conditionNode (like search all parameters where the parent of this node is a house) list - a checkBoxTreeItem node, through which the algorithm is searching for a specific node searchedNode - is the node we are searching. at the start, the selected node which throws the actionlistener conditionNode - extras we want, like that the parent is a specific node.
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.recExpandTree(TreeItem< String > tree)
list - TreeItem the right trees from the tab on the right side from the resultswindow node - the node which activated the actionlistener expands the tree tree
void sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.selectNode(CheckBoxTreeItem< String > node, CheckBoxTreeItem< String > setNode)
Methode checks how the node is set (isSelected, isNotSelected), and than we set the other node also that way node - which throws the action listener setNode - node which we want be selected or unselected
static TreeItem<String> sgs.controller.fileManagement.csvConstruction.CheckBoxActionListener.getResultsCollection()
the choosenCollectionTree;