.TH "RAPSim/src/sgs/model/variables/collector Directory Reference" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RAPSim/src/sgs/model/variables/collector Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVariableCollection\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableCollector\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableCollectorAvg\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableCollectorMax\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableCollectorMin\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableCollectorSum\&.java\fP"
.br
.ti -1c
.RI "file \fBVariableOwner\&.java\fP"
.br
.in -1c
