.TH "sgs.view.SpeedChanger" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.SpeedChanger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpeedChanger\fP (final \fBTimeThread\fP timeThread)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static boolean \fBisRunning\fP = false"
.br
.ti -1c
.RI "static int \fBMIN\fP =10"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int \fBmapedValue\fP (double expValue)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This code was edited or generated using CloudGarden's Jigloo SWT/Swing GUI Builder, which is free for non-commercial use\&. If Jigloo is being used commercially (ie, by a corporation, company or business for any purpose whatever) then you should purchase a license for each developer using Jigloo\&. Please visit www\&.cloudgarden\&.com for details\&. Use of Jigloo implies acceptance of these licensing terms\&. A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE\&.
.PP
\fBAuthor:\fP
.RS 4
Tobi, Schweiger, Huber, Pöchacker 
.RE
.PP

.PP
Definition at line 46 of file SpeedChanger\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.SpeedChanger\&.SpeedChanger (final \fBTimeThread\fPtimeThread)"

.PP
Definition at line 64 of file SpeedChanger\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int sgs\&.view\&.SpeedChanger\&.mapedValue (doubleexpValue)\fC [protected]\fP"

.PP
Definition at line 209 of file SpeedChanger\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "boolean sgs\&.view\&.SpeedChanger\&.isRunning = false\fC [static]\fP"

.PP
Definition at line 51 of file SpeedChanger\&.java\&.
.SS "int sgs\&.view\&.SpeedChanger\&.MIN =10\fC [static]\fP"

.PP
Definition at line 56 of file SpeedChanger\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
