.TH "sgs.model.objectModels" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractConsumerModel\fP"
.br
.ti -1c
.RI "class \fBAbstractCustomConsumerModel\fP"
.br
.ti -1c
.RI "class \fBAbstractCustomPowerPlantModel\fP"
.br
.ti -1c
.RI "class \fBAbstractFossilFuelPowerPlantModel\fP"
.br
.ti -1c
.RI "class \fBAbstractModel\fP"
.br
.ti -1c
.RI "class \fBAbstractPowerLineModel\fP"
.br
.ti -1c
.RI "class \fBAbstractPowerPlantModel\fP"
.br
.ti -1c
.RI "class \fBAbstractSolarPowerPlantModel\fP"
.br
.ti -1c
.RI "class \fBAbstractWindPowerPlantModel\fP"
.br
.ti -1c
.RI "class \fBConstantDemandModel\fP"
.br
.ti -1c
.RI "class \fBConstantPowerModel\fP"
.br
.ti -1c
.RI "class \fBFossilFuelModel\fP"
.br
.ti -1c
.RI "class \fBPiEquivalentPowerLine\fP"
.br
.ti -1c
.RI "class \fBRandomWindTurbineModel\fP"
.br
.ti -1c
.RI "class \fBResidentialAverageLoadCurveModel\fP"
.br
.ti -1c
.RI "class \fBSolarPeakPowerModel\fP"
.br
.ti -1c
.RI "class \fBSolarSquareMeterModel\fP"
.br
.ti -1c
.RI "interface \fBTimeSeriesModel\fP"
.br
.ti -1c
.RI "class \fBUsualWindTurbineModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
