.TH "sgs.model.variables" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.variables \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcollector\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractValue\fP"
.br
.ti -1c
.RI "enum \fBEnumPV\fP"
.br
.ti -1c
.RI "enum \fBEnumUnit\fP"
.br
.ti -1c
.RI "class \fBNumericValue\fP"
.br
.ti -1c
.RI "class \fBSingleVariable\fP"
.br
.ti -1c
.RI "class \fBStringValue\fP"
.br
.ti -1c
.RI "class \fBVariableProperties\fP"
.br
.ti -1c
.RI "class \fBVariableSet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
