.TH "sgs.model.objectModels.AbstractCustomConsumerModel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.AbstractCustomConsumerModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.objectModels\&.AbstractConsumerModel\fP\&.
.PP
Inherited by \fBsgs\&.model\&.objectModels\&.ConstantDemandModel\fP, and \fBsgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractCustomConsumerModel\fP (\fBCustomConsumer\fP \fBconsumer\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
bbreilin 
.RE
.PP

.PP
Definition at line 9 of file AbstractCustomConsumerModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.objectModels\&.AbstractCustomConsumerModel\&.AbstractCustomConsumerModel (\fBCustomConsumer\fPconsumer)"

.PP
Definition at line 11 of file AbstractCustomConsumerModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
