.TH "sgs.view.BottomPanel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.BottomPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JToolBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "JButton \fBaddControl_BottomButton\fP (String iconPath, String toolTip, ActionListener l)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dimension \fBdefaultButtonDimension\fP = new Dimension(85,60)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Panel with all elements at the bottom of the GUI\&.
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 16 of file BottomPanel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JButton sgs\&.view\&.BottomPanel\&.addControl_BottomButton (StringiconPath, StringtoolTip, ActionListenerl)"
Make button, add Action listener button, add the button to the view\&. 
.PP
\fBParameters:\fP
.RS 4
\fIiconPath\fP - path to icon (+name) 
.br
\fIl\fP - ActionListener to add, can be null\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
JButton 
.RE
.PP

.PP
Definition at line 27 of file BottomPanel\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Dimension sgs\&.view\&.BottomPanel\&.defaultButtonDimension = new Dimension(85,60)\fC [static]\fP"

.PP
Definition at line 19 of file BottomPanel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
