.TH "sgs.view.AlgorithmDescriptionDialog" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.AlgorithmDescriptionDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithmDescriptionDialog\fP (JFrame owner, \fBAbstractDistributionAlgorithm\fP algorithm)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This code was edited or generated using CloudGarden's Jigloo SWT/Swing GUI Builder, which is free for non-commercial use\&. If Jigloo is being used commercially (ie, by a corporation, company or business for any purpose whatever) then you should purchase a license for each developer using Jigloo\&. Please visit www\&.cloudgarden\&.com for details\&. Use of Jigloo implies acceptance of these licensing terms\&. A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE\&. 
.PP
Definition at line 25 of file AlgorithmDescriptionDialog\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.AlgorithmDescriptionDialog\&.AlgorithmDescriptionDialog (JFrameowner, \fBAbstractDistributionAlgorithm\fPalgorithm)"

.PP
\fBParameters:\fP
.RS 4
\fIowner\fP 
.br
\fIalgorithm\fP 
.RE
.PP

.PP
Definition at line 57 of file AlgorithmDescriptionDialog\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void sgs\&.view\&.AlgorithmDescriptionDialog\&.main (String[]args)\fC [static]\fP"
Auto-generated main method to display this JDialog 
.PP
Definition at line 34 of file AlgorithmDescriptionDialog\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
