.TH "sgs.model.variables.collector" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.variables.collector \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVariableCollection\fP"
.br
.ti -1c
.RI "class \fBVariableCollector\fP"
.br
.ti -1c
.RI "class \fBVariableCollectorAvg\fP"
.br
.ti -1c
.RI "class \fBVariableCollectorMax\fP"
.br
.ti -1c
.RI "class \fBVariableCollectorMin\fP"
.br
.ti -1c
.RI "class \fBVariableCollectorSum\fP"
.br
.ti -1c
.RI "interface \fBVariableOwner\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
