.TH "sgs.model.objectModels.FossilFuelModel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.FossilFuelModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.objectModels\&.AbstractFossilFuelPowerPlantModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFossilFuelModel\fP (\fBFossilFuelPowerPlant\fP \fBpowerPlant\fP)"
.br
.ti -1c
.RI "void \fBupdateVariables\fP (GregorianCalendar currentTime, \fBWeather\fP weather, int resolution)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitVariableSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
mpoechac 
.RE
.PP

.PP
Definition at line 20 of file FossilFuelModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.objectModels\&.FossilFuelModel\&.FossilFuelModel (\fBFossilFuelPowerPlant\fPpowerPlant)"

.PP
Definition at line 28 of file FossilFuelModel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.model\&.objectModels\&.FossilFuelModel\&.initVariableSet ()\fC [protected]\fP, \fC [virtual]\fP"
Implemented in the model and called in the constructor of an AbstractObjectnameModel super-class 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 69 of file FossilFuelModel\&.java\&.
.SS "void sgs\&.model\&.objectModels\&.FossilFuelModel\&.updateVariables (GregorianCalendarcurrentTime, \fBWeather\fPweather, intresolution)\fC [virtual]\fP"
Should be implemented in the model to calculate new variable values 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 40 of file FossilFuelModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
