.TH "sgs.controller.simulation.BusNettoPowerComparator" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.simulation.BusNettoPowerComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparator< Bus >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBBus\fP a, \fBBus\fP b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file BusNettoPowerComparator\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int sgs\&.controller\&.simulation\&.BusNettoPowerComparator\&.compare (\fBBus\fPa, \fBBus\fPb)"

.PP
Definition at line 11 of file BusNettoPowerComparator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
