.TH "sgs.view.PropertiesDialog" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.PropertiesDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog, and KeyListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPropertiesDialog\fP (\fBSgsGridModel\fP gridModel, int x, int y)"
.br
.ti -1c
.RI "\fBPropertiesDialog\fP (\fBSgsGridModel\fP gridModel, \fBSmartGridObject\fP gObject)"
.br
.ti -1c
.RI "void \fBkeyPressed\fP (KeyEvent e)"
.br
.ti -1c
.RI "void \fBkeyReleased\fP (KeyEvent e)"
.br
.ti -1c
.RI "void \fBkeyTyped\fP (KeyEvent e)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static File \fBgetf\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4

.RE
.PP

.PP
Definition at line 42 of file PropertiesDialog\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.PropertiesDialog\&.PropertiesDialog (\fBSgsGridModel\fPgridModel, intx, inty)"

.PP
\fBParameters:\fP
.RS 4
\fIgridModel\fP 
.br
\fI_x\fP 
.br
\fI_y\fP 
.RE
.PP

.PP
Definition at line 78 of file PropertiesDialog\&.java\&.
.SS "sgs\&.view\&.PropertiesDialog\&.PropertiesDialog (\fBSgsGridModel\fPgridModel, \fBSmartGridObject\fPgObject)"
Open a \fBPropertiesDialog\fP for the specified object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgridModel\fP 
.br
\fI_x\fP 
.br
\fI_y\fP 
.RE
.PP

.PP
Definition at line 89 of file PropertiesDialog\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static File sgs\&.view\&.PropertiesDialog\&.getf ()\fC [static]\fP"

.PP
Definition at line 68 of file PropertiesDialog\&.java\&.
.SS "void sgs\&.view\&.PropertiesDialog\&.keyPressed (KeyEvente)"

.PP
Definition at line 373 of file PropertiesDialog\&.java\&.
.SS "void sgs\&.view\&.PropertiesDialog\&.keyReleased (KeyEvente)"

.PP
Definition at line 377 of file PropertiesDialog\&.java\&.
.SS "void sgs\&.view\&.PropertiesDialog\&.keyTyped (KeyEvente)"

.PP
Definition at line 384 of file PropertiesDialog\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
