.TH "sgs.model.variables.EnumPV" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.variables.EnumPV \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnumUnit\fP \fBgetUnit\fP ()"
.br
.ti -1c
.RI "Object \fBgetDefaultValue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpowerDemand\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBpowerConsumption\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBpowerProductionOptimal\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBpowerProduction\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBpowerProductionNeeded\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBnominalVoltage\fP =(\fBEnumUnit\&.volt\fP, 1\&.0)"
.br
.ti -1c
.RI "\fBcurrentVoltage\fP =(\fBEnumUnit\&.volt\fP, 1\&.0)"
.br
.ti -1c
.RI "\fBvoltageAngle\fP =(\fBEnumUnit\&.degree\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBmaxPowerTransport\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBtransportPowerDecrement\fP =(\fBEnumUnit\&.none\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBresistance\fP =(\fBEnumUnit\&.ohm\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBpowerLineCharge\fP =(\fBEnumUnit\&.ohm\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBcurrentCurrent\fP =(\fBEnumUnit\&.ampere\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBcurrentPowerLoss\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.ti -1c
.RI "\fBcurrentPowerTransport\fP =(\fBEnumUnit\&.watt\fP, 0\&.0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enum for predefined variables\&. Holds the variable name and their ISO unit\&.
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 10 of file EnumPV\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Object sgs\&.model\&.variables\&.EnumPV\&.getDefaultValue ()"

.PP
\fBReturns:\fP
.RS 4
the default value defined for this variable 
.RE
.PP

.PP
Definition at line 56 of file EnumPV\&.java\&.
.SS "\fBEnumUnit\fP sgs\&.model\&.variables\&.EnumPV\&.getUnit ()"

.PP
\fBReturns:\fP
.RS 4
the unit defined for this variable 
.RE
.PP

.PP
Definition at line 50 of file EnumPV\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "sgs\&.model\&.variables\&.EnumPV\&.currentCurrent =(\fBEnumUnit\&.ampere\fP, 0\&.0)"

.PP
Definition at line 28 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.currentPowerLoss =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 29 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.currentPowerTransport =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 30 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.currentVoltage =(\fBEnumUnit\&.volt\fP, 1\&.0)"

.PP
Definition at line 20 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.maxPowerTransport =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 24 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.nominalVoltage =(\fBEnumUnit\&.volt\fP, 1\&.0)"

.PP
Definition at line 19 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerConsumption =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 13 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerDemand =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 12 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerLineCharge =(\fBEnumUnit\&.ohm\fP, 0\&.0)"

.PP
Definition at line 27 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerProduction =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 16 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerProductionNeeded =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 17 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.powerProductionOptimal =(\fBEnumUnit\&.watt\fP, 0\&.0)"

.PP
Definition at line 15 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.resistance =(\fBEnumUnit\&.ohm\fP, 0\&.0)"

.PP
Definition at line 26 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.transportPowerDecrement =(\fBEnumUnit\&.none\fP, 0\&.0)"

.PP
Definition at line 25 of file EnumPV\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumPV\&.voltageAngle =(\fBEnumUnit\&.degree\fP, 0\&.0)"

.PP
Definition at line 21 of file EnumPV\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
