.TH "sgs.controller.simulation._TestingAlgorithm" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.simulation._TestingAlgorithm \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_TestingAlgorithm\fP (\fBGridController\fP gridController)"
.br
.ti -1c
.RI "void \fBinitializeAlgorithm\fP ()"
.br
.ti -1c
.RI "void \fBgridChanged\fP ()"
.br
.ti -1c
.RI "void \fBcalculationStep\fP ()"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "void \fBsimulationStarted\fP ()"
.br
.ti -1c
.RI "void \fBsimulationStopped\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetPropertiesForVariables\fP ()"
.br
.ti -1c
.RI "void \fBsetPropertiesForBusAndPath\fP ()"
.br
.ti -1c
.RI "void \fBunloadAlgorithm\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file _TestingAlgorithm\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.controller\&.simulation\&._TestingAlgorithm\&._TestingAlgorithm (\fBGridController\fPgridController)"
Constructor for reflection\&. Must (only) use parameter \fBGridController\fP\&. 
.PP
Definition at line 24 of file _TestingAlgorithm\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.calculationStep ()\fC [virtual]\fP"
Calculate grid for one simulation step\&. 
.PP
.RS 4
Buses and Paths are locked before\&. Grid/View-Repaint is automatically called after the function\&. 
.RE
.PP

.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 62 of file _TestingAlgorithm\&.java\&.
.SS "String sgs\&.controller\&.simulation\&._TestingAlgorithm\&.getDescription ()\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
description of the specific algorithm used for the 'Info' button 
.RE
.PP

.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 79 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.gridChanged ()\fC [virtual]\fP"
Is called if the Grid is modified\&. 
.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 41 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.initializeAlgorithm ()"

.PP
Definition at line 32 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.setPropertiesForBusAndPath ()\fC [protected]\fP, \fC [virtual]\fP"
Set \fBSgsGridModel\&.resistanceAttributes\fP, busVariableCollection, pathVariableCollection if used\&. 
.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 56 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.setPropertiesForVariables ()\fC [protected]\fP, \fC [virtual]\fP"
Set the algorithm specific variables with help of the super class methods\&. 
.PP
\fBSee Also:\fP
.RS 4
\fBselectClass(Class)\fP, \fBsetProperties(boolean,boolean,EnumPV[])\fP, \fBinitializeVariables()\fP 
.RE
.PP

.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 46 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.simulationStarted ()\fC [virtual]\fP"
Called by time thread\&. Write interesting contents of the simulation to a file\&. Called directly after the simulation was started\&. Use this to make a LOG file if one is used\&. 
.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 84 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.simulationStopped ()\fC [virtual]\fP"
Called directly after the simulation was stopped\&. Use this to flush/close a log file if one was used\&. 
.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 89 of file _TestingAlgorithm\&.java\&.
.SS "void sgs\&.controller\&.simulation\&._TestingAlgorithm\&.unloadAlgorithm ()\fC [protected]\fP, \fC [virtual]\fP"
Free external resources used by this algorithm\&. 
.PP
Implements \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.PP
Definition at line 74 of file _TestingAlgorithm\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
