.TH "sgs.model.gridObjects.Consumer" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridObjects.Consumer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.gridObjects\&.ProSumer\fP\&.
.PP
Inherited by \fBsgs\&.model\&.gridObjects\&.CustomConsumer\fP, and \fBsgs\&.model\&.gridObjects\&.House\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsumer\fP ()"
.br
.ti -1c
.RI "\fBAbstractConsumerModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBAbstractConsumerModel\fP \fBmodel\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
bbreilin 
.RE
.PP

.PP
Definition at line 11 of file Consumer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.gridObjects\&.Consumer\&.Consumer ()"

.PP
Definition at line 13 of file Consumer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAbstractConsumerModel\fP sgs\&.model\&.gridObjects\&.Consumer\&.getModel ()"

.PP
Definition at line 19 of file Consumer\&.java\&.
.SS "void sgs\&.model\&.gridObjects\&.Consumer\&.setModel (\fBAbstractConsumerModel\fPmodel)"

.PP
Definition at line 23 of file Consumer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
