.TH "sgs.controller.interfaces.GridChangeListener" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.interfaces.GridChangeListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgridChanged\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file GridChangeListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.controller\&.interfaces\&.GridChangeListener\&.gridChanged ()"
Notifies the Object, that the grid has changed in some way\&. 
.PP
Implemented in \fBsgs\&.controller\&.simulation\&.DCPowerFlowCalculator\fP, \fBsgs\&.controller\&.simulation\&.SimplePowerDistribution\fP, \fBsgs\&.controller\&.simulation\&.AbstractDistributionAlgorithm\fP, \fBsgs\&.controller\&.simulation\&.ACPowerFlowCalculator\fP, and \fBsgs\&.controller\&.simulation\&._TestingAlgorithm\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
