.TH "sgs.model.objectModels.ResidentialAverageLoadCurveModel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.ResidentialAverageLoadCurveModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.objectModels\&.AbstractCustomConsumerModel\fP, and \fBsgs\&.model\&.objectModels\&.TimeSeriesModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResidentialAverageLoadCurveModel\fP (\fBCustomConsumer\fP \fBconsumer\fP)"
.br
.ti -1c
.RI "void \fBupdateVariables\fP (GregorianCalendar currentTime, \fBWeather\fP weather, int resolution)"
.br
.ti -1c
.RI "void \fBloadDataFromFile\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitVariableSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
bbreilin, mpoechacker 
.RE
.PP

.PP
Definition at line 22 of file ResidentialAverageLoadCurveModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\&.ResidentialAverageLoadCurveModel (\fBCustomConsumer\fPconsumer)"

.PP
Definition at line 38 of file ResidentialAverageLoadCurveModel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\&.initVariableSet ()\fC [protected]\fP, \fC [virtual]\fP"
Implemented in the model and called in the constructor of an AbstractObjectnameModel super-class 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 51 of file ResidentialAverageLoadCurveModel\&.java\&.
.SS "void sgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\&.loadDataFromFile ()"

.PP
Implements \fBsgs\&.model\&.objectModels\&.TimeSeriesModel\fP\&.
.PP
Definition at line 65 of file ResidentialAverageLoadCurveModel\&.java\&.
.SS "void sgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\&.updateVariables (GregorianCalendarcurrentTime, \fBWeather\fPweather, intresolution)\fC [virtual]\fP"
Should be implemented in the model to calculate new variable values 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 58 of file ResidentialAverageLoadCurveModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
