.TH "sgs.controller.MenuController" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.MenuController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuController\fP (MenuViewI menuView, JFrame frame, \fBGridController\fP gridController, \fBTimeThread\fP timeThread, PrimaryView primaryView)"
.br
.ti -1c
.RI "void \fBaddMenu\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetTreeNotEmpty\fP (boolean b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "JCheckBoxMenuItem \fBallLegendsCB\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static JMenuItem \fBopenSlider\fP"
.br
.ti -1c
.RI "static boolean \fBtreeNotEmpty\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller component for the menu\&. 
.PP
\fBAuthor:\fP
.RS 4
Tobi, Kristofer Schweiger, Huber 
.RE
.PP

.PP
Definition at line 46 of file MenuController\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.controller\&.MenuController\&.MenuController (MenuViewImenuView, JFrameframe, \fBGridController\fPgridController, \fBTimeThread\fPtimeThread, PrimaryViewprimaryView)"
Constructor for controller 
.PP
\fBParameters:\fP
.RS 4
\fImenuView\fP 
.br
\fIframe\fP 
.br
\fIgridController\fP 
.br
\fItimeThread\fP 
.br
\fIprimaryView\fP 
.RE
.PP

.PP
Definition at line 72 of file MenuController\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.controller\&.MenuController\&.addMenu ()"

.PP
\fBParameters:\fP
.RS 4
\fIframe\fP 
.RE
.PP

.PP
Definition at line 114 of file MenuController\&.java\&.
.SS "static void sgs\&.controller\&.MenuController\&.setTreeNotEmpty (booleanb)\fC [static]\fP"

.PP
Definition at line 641 of file MenuController\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "JCheckBoxMenuItem sgs\&.controller\&.MenuController\&.allLegendsCB"

.PP
Definition at line 52 of file MenuController\&.java\&.
.SS "JMenuItem sgs\&.controller\&.MenuController\&.openSlider\fC [static]\fP"

.PP
Definition at line 51 of file MenuController\&.java\&.
.SS "boolean sgs\&.controller\&.MenuController\&.treeNotEmpty = false\fC [static]\fP"

.PP
Definition at line 60 of file MenuController\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
