.TH "sgs.model.ProgramConstants" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.ProgramConstants \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static String \fBdataPath\fP = 'Data2/'"
.br
.ti -1c
.RI "static File \fBdefaultSimulationFile\fP = new File(\fBdataPath\fP+'data\&.zip')"
.br
.ti -1c
.RI "static File \fBparameterFile\fP = new File(\fBdataPath\fP+'parameters\&.zip')"
.br
.ti -1c
.RI "static DateFormat \fBdf\fP = new SimpleDateFormat('yyyy\&.MM\&.dd - HH:mm')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface holding a few constants for the Controller\&. Use e\&.g\&. with static import\&. Variables in interface are automatically final\&.
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 15 of file ProgramConstants\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "String sgs\&.model\&.ProgramConstants\&.dataPath = 'Data2/'\fC [static]\fP"
path to image files and other application data files 
.PP
Definition at line 18 of file ProgramConstants\&.java\&.
.SS "File sgs\&.model\&.ProgramConstants\&.defaultSimulationFile = new File(\fBdataPath\fP+'data\&.zip')\fC [static]\fP"
default file in dataPath where project is stored 
.PP
Definition at line 21 of file ProgramConstants\&.java\&.
.SS "DateFormat sgs\&.model\&.ProgramConstants\&.df = new SimpleDateFormat('yyyy\&.MM\&.dd - HH:mm')\fC [static]\fP"
the date format used 
.PP
Definition at line 27 of file ProgramConstants\&.java\&.
.SS "File sgs\&.model\&.ProgramConstants\&.parameterFile = new File(\fBdataPath\fP+'parameters\&.zip')\fC [static]\fP"
file in dataPath where the program configuration is stored 
.PP
Definition at line 24 of file ProgramConstants\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
