.TH "sgs.view.ColorLegendPanel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.ColorLegendPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JPanel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorLegendPanel\fP ()"
.br
.ti -1c
.RI "void \fBrepaintLegend\fP (boolean[] overlayNumberArray)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ColorLegendPanel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.ColorLegendPanel\&.ColorLegendPanel ()"

.PP
Definition at line 23 of file ColorLegendPanel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.view\&.ColorLegendPanel\&.repaintLegend (boolean[]overlayNumberArray)"

.PP
Definition at line 52 of file ColorLegendPanel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
