.TH "sgs.controller.EditFunctionController" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.EditFunctionController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditFunctionController\fP (\fBSmartGridObject\fP[][] gridObjects, LinkedList< \fBSmartGridObject\fP > gridObjectList, \fBSmartGridObject\fP gObj, \fBSgsGridModel\fP gridModel)"
.br
.ti -1c
.RI "void \fBUndoManager\fP (\fBSmartGridObject\fP gobj)"
.br
.ti -1c
.RI "void \fBEditUndoFunction\fP ()  throws CannotUndoException"
.br
.ti -1c
.RI "void \fBEditRedoFunction\fP ()  throws CannotRedoException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file EditFunctionController\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.controller\&.EditFunctionController\&.EditFunctionController (\fBSmartGridObject\fPgridObjects[][], LinkedList< \fBSmartGridObject\fP >gridObjectList, \fBSmartGridObject\fPgObj, \fBSgsGridModel\fPgridModel)"

.PP
\fBParameters:\fP
.RS 4
\fIgridObjects\fP 
.br
\fIgridObjectList\fP 
.br
\fIgObj\fP 
.br
\fIgridModel\fP 
.RE
.PP

.PP
Definition at line 33 of file EditFunctionController\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.controller\&.EditFunctionController\&.EditRedoFunction () throws CannotRedoException"

.PP
Definition at line 73 of file EditFunctionController\&.java\&.
.SS "void sgs\&.controller\&.EditFunctionController\&.EditUndoFunction () throws CannotUndoException"

.PP
\fBAuthor:\fP
.RS 4
hs 
.RE
.PP

.PP
Definition at line 64 of file EditFunctionController\&.java\&.
.SS "void sgs\&.controller\&.EditFunctionController\&.UndoManager (\fBSmartGridObject\fPgobj)"

.PP
\fBParameters:\fP
.RS 4
\fIgobj\fP 
.RE
.PP

.PP
Definition at line 45 of file EditFunctionController\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
