.TH "sgs.model.objectModels.TimeSeriesModel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.TimeSeriesModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBloadDataFromFile\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBPERIOD_DAILY\fP = 0"
.br
.ti -1c
.RI "static int \fBPERIOD_WEEKLY\fP = 1"
.br
.ti -1c
.RI "static int \fBPERIOD_MONTHLY\fP = 2"
.br
.ti -1c
.RI "static int \fBPERIOD_ANNUALY\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
bbreilin 
.RE
.PP

.PP
Definition at line 7 of file TimeSeriesModel\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.model\&.objectModels\&.TimeSeriesModel\&.loadDataFromFile ()"

.PP
Implemented in \fBsgs\&.model\&.objectModels\&.ResidentialAverageLoadCurveModel\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sgs\&.model\&.objectModels\&.TimeSeriesModel\&.PERIOD_ANNUALY = 3\fC [static]\fP"

.PP
Definition at line 11 of file TimeSeriesModel\&.java\&.
.SS "int sgs\&.model\&.objectModels\&.TimeSeriesModel\&.PERIOD_DAILY = 0\fC [static]\fP"

.PP
Definition at line 8 of file TimeSeriesModel\&.java\&.
.SS "int sgs\&.model\&.objectModels\&.TimeSeriesModel\&.PERIOD_MONTHLY = 2\fC [static]\fP"

.PP
Definition at line 10 of file TimeSeriesModel\&.java\&.
.SS "int sgs\&.model\&.objectModels\&.TimeSeriesModel\&.PERIOD_WEEKLY = 1\fC [static]\fP"

.PP
Definition at line 9 of file TimeSeriesModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
