.TH "sgs.model.other.JTableModelSGS" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.other.JTableModelSGS \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJTableModelSGS\fP (Object[][] data, Object[] columnNames)"
.br
.ti -1c
.RI "boolean \fBisCellEditable\fP (int row, int column)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TableModel for SGS\&. Should have advanced configurations of editable fields later\&. // TODO //
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 11 of file JTableModelSGS\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.other\&.JTableModelSGS\&.JTableModelSGS (Objectdata[][], Object[]columnNames)"

.PP
Definition at line 15 of file JTableModelSGS\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean sgs\&.model\&.other\&.JTableModelSGS\&.isCellEditable (introw, intcolumn)"

.PP
Definition at line 21 of file JTableModelSGS\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
