.TH "sgs.view.FirstStartWindow" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.FirstStartWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirstStartWindow\fP (JFrame parent, final \fBProgramParametersSaved\fP params)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBstart\fP (final JFrame parent, final \fBProgramParametersSaved\fP params)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This code was edited or generated using CloudGarden's Jigloo SWT/Swing GUI Builder, which is free for non-commercial use\&. If Jigloo is being used commercially (ie, by a corporation, company or business for any purpose whatever) then you should purchase a license for each developer using Jigloo\&. Please visit www\&.cloudgarden\&.com for details\&. Use of Jigloo implies acceptance of these licensing terms\&. A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE\&. 
.PP
Definition at line 28 of file FirstStartWindow\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.FirstStartWindow\&.FirstStartWindow (JFrameparent, final \fBProgramParametersSaved\fPparams)"

.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.PP
Definition at line 46 of file FirstStartWindow\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void sgs\&.view\&.FirstStartWindow\&.start (final JFrameparent, final \fBProgramParametersSaved\fPparams)\fC [static]\fP"

.PP
Definition at line 34 of file FirstStartWindow\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
