.TH "sgs.model.variables.EnumUnit" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.variables.EnumUnit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnumUnit\fP (String \fBshortName\fP)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwatt\fP =('W')"
.br
.ti -1c
.RI "\fBvolt\fP =('V')"
.br
.ti -1c
.RI "\fBampere\fP =('A')"
.br
.ti -1c
.RI "\fBohm\fP =('OHM')"
.br
.ti -1c
.RI "\fBdegree\fP =('°')"
.br
.ti -1c
.RI "\fBsquareMeters\fP =('m²')"
.br
.ti -1c
.RI "\fBkilometers\fP =('km')"
.br
.ti -1c
.RI "\fBpercent\fP =('%')"
.br
.ti -1c
.RI "\fBpercentDiv100\fP =('% /100')"
.br
.ti -1c
.RI "\fBnone\fP =('')"
.br
.ti -1c
.RI "\fBmeterPerSecond\fP =('m/s')"
.br
.ti -1c
.RI "\fBkiloWattHour\fP =('kWh')"
.br
.ti -1c
.RI "\fBhertz\fP =('Hz')"
.br
.ti -1c
.RI "\fBliter\fP =('l')"
.br
.ti -1c
.RI "\fBTODO\fP =('???')"
.br
.ti -1c
.RI "String \fBshortName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit enum to be used with \fBVariableSet\fP\&.
.PP
TODO: Add all needed units\&. TODO: Unit calculation, handling of multiplication etc\&. ? -> Special unit with String-like representation?
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger, bbreilin 
.RE
.PP

.PP
Definition at line 12 of file EnumUnit\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.variables\&.EnumUnit\&.EnumUnit (StringshortName)"

.PP
Definition at line 31 of file EnumUnit\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String sgs\&.model\&.variables\&.EnumUnit\&.toString ()"

.PP
Definition at line 36 of file EnumUnit\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "sgs\&.model\&.variables\&.EnumUnit\&.ampere =('A')"

.PP
Definition at line 16 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.degree =('°')"

.PP
Definition at line 18 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.hertz =('Hz')"

.PP
Definition at line 26 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.kilometers =('km')"

.PP
Definition at line 20 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.kiloWattHour =('kWh')"

.PP
Definition at line 25 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.liter =('l')"

.PP
Definition at line 27 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.meterPerSecond =('m/s')"

.PP
Definition at line 24 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.none =('')"

.PP
Definition at line 23 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.ohm =('OHM')"

.PP
Definition at line 17 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.percent =('%')"

.PP
Definition at line 21 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.percentDiv100 =('% /100')"

.PP
Definition at line 22 of file EnumUnit\&.java\&.
.SS "String sgs\&.model\&.variables\&.EnumUnit\&.shortName"

.PP
Definition at line 30 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.squareMeters =('m²')"

.PP
Definition at line 19 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.TODO =('???')"

.PP
Definition at line 28 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.volt =('V')"

.PP
Definition at line 15 of file EnumUnit\&.java\&.
.SS "sgs\&.model\&.variables\&.EnumUnit\&.watt =('W')"

.PP
Definition at line 14 of file EnumUnit\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
