.TH "sgs.model.gridObjects.WindTurbinePowerPlant" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridObjects.WindTurbinePowerPlant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.gridObjects\&.PowerPlant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindTurbinePowerPlant\fP ()"
.br
.ti -1c
.RI "\fBGridDataEnum\fP \fBgetEnum\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBSmartGridObject\fP\&. 
.PP
\fBAuthor:\fP
.RS 4
tobi, Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 11 of file WindTurbinePowerPlant\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.gridObjects\&.WindTurbinePowerPlant\&.WindTurbinePowerPlant ()"
Constructor 
.PP
Definition at line 16 of file WindTurbinePowerPlant\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGridDataEnum\fP sgs\&.model\&.gridObjects\&.WindTurbinePowerPlant\&.getEnum ()\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
corresponding enum for this object\&. 
.RE
.PP

.PP
Implements \fBsgs\&.model\&.gridObjects\&.SmartGridObject\fP\&.
.PP
Definition at line 25 of file WindTurbinePowerPlant\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
