.TH "sgs.model.gridData.Overlay.OverlayColorEnum" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridData.Overlay.OverlayColorEnum \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRED\fP"
.br
.ti -1c
.RI "\fBORANGE\fP"
.br
.ti -1c
.RI "\fBYELLOW\fP"
.br
.ti -1c
.RI "\fBGREEN\fP"
.br
.ti -1c
.RI "\fBTURQUOIS\fP"
.br
.ti -1c
.RI "\fBBLUE\fP"
.br
.ti -1c
.RI "\fBVIOLET\fP"
.br
.ti -1c
.RI "\fBRED_GREEN\fP"
.br
.ti -1c
.RI "\fBBLACK_BLUE\fP"
.br
.ti -1c
.RI "\fBBLACK_WHITE\fP"
.br
.ti -1c
.RI "\fBRED_BLUE\fP"
.br
.ti -1c
.RI "\fBRED_GREEN_BLUE\fP"
.br
.ti -1c
.RI "\fBGREEN_YELLOW_RED\fP"
.br
.ti -1c
.RI "\fBBLACK_WHITE_BLACK\fP"
.br
.ti -1c
.RI "\fBRED_WHITE_BLUE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enum defining the dynamic overlay color in the grid 
.PP
Definition at line 15 of file Overlay\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.BLACK_BLUE"

.PP
Definition at line 22 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.BLACK_WHITE"

.PP
Definition at line 23 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.BLACK_WHITE_BLACK"

.PP
Definition at line 29 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.BLUE"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.GREEN"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.GREEN_YELLOW_RED"

.PP
Definition at line 28 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.ORANGE"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.RED"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.RED_BLUE"

.PP
Definition at line 24 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.RED_GREEN"

.PP
Definition at line 21 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.RED_GREEN_BLUE"

.PP
Definition at line 27 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.RED_WHITE_BLUE"

.PP
Definition at line 30 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.TURQUOIS"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.VIOLET"

.PP
Definition at line 18 of file Overlay\&.java\&.
.SS "sgs\&.model\&.gridData\&.Overlay\&.OverlayColorEnum\&.YELLOW"

.PP
Definition at line 18 of file Overlay\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
