.TH "sgs.model.gridObjects.PowerPlant" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridObjects.PowerPlant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.gridObjects\&.ProSumer\fP\&.
.PP
Inherited by \fBsgs\&.model\&.gridObjects\&.CustomPowerPlant\fP, \fBsgs\&.model\&.gridObjects\&.FossilFuelPowerPlant\fP, \fBsgs\&.model\&.gridObjects\&.SolarPowerPlant\fP, and \fBsgs\&.model\&.gridObjects\&.WindTurbinePowerPlant\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPowerPlant\fP ()"
.br
.ti -1c
.RI "\fBAbstractPowerPlantModel\fP \fBgetModel\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBAbstractPowerPlantModel\fP \fBmodel\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBSmartGridObject\fP\&. 
.PP
\fBAuthor:\fP
.RS 4
tobi, Kristofer Schweiger, bbreilin 
.RE
.PP

.PP
Definition at line 12 of file PowerPlant\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.gridObjects\&.PowerPlant\&.PowerPlant ()"
Abstract constructor 
.PP
Definition at line 16 of file PowerPlant\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAbstractPowerPlantModel\fP sgs\&.model\&.gridObjects\&.PowerPlant\&.getModel ()"

.PP
Definition at line 22 of file PowerPlant\&.java\&.
.SS "void sgs\&.model\&.gridObjects\&.PowerPlant\&.setModel (\fBAbstractPowerPlantModel\fPmodel)"

.PP
Definition at line 25 of file PowerPlant\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
