.TH "sgs.model.other.JTableModelVariables" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.other.JTableModelVariables \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AbstractTableModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJTableModelVariables\fP (JTable table, \fBVariableSet\fP variableSet)"
.br
.ti -1c
.RI "int \fBgetColumnCount\fP ()"
.br
.ti -1c
.RI "String \fBgetColumnName\fP (int col)"
.br
.ti -1c
.RI "int \fBgetRowCount\fP ()"
.br
.ti -1c
.RI "void \fBsetValueAt\fP (Object aValue, int row, int col)"
.br
.ti -1c
.RI "Object \fBgetValueAt\fP (int row, int col)"
.br
.ti -1c
.RI "\fBSingleVariable\fP \fBgetVariableAt\fP (int row)"
.br
.ti -1c
.RI "boolean \fBisCellEditable\fP (int row, int column)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TableModel for SGS\&. Should have advanced configurations of editable fields later\&. // TODO //
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 15 of file JTableModelVariables\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.other\&.JTableModelVariables\&.JTableModelVariables (JTabletable, \fBVariableSet\fPvariableSet)"

.PP
Definition at line 22 of file JTableModelVariables\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int sgs\&.model\&.other\&.JTableModelVariables\&.getColumnCount ()"

.PP
Definition at line 34 of file JTableModelVariables\&.java\&.
.SS "String sgs\&.model\&.other\&.JTableModelVariables\&.getColumnName (intcol)"
Getter, 
.PP
\fBReturns:\fP
.RS 4
column name 
.RE
.PP

.PP
Definition at line 39 of file JTableModelVariables\&.java\&.
.SS "int sgs\&.model\&.other\&.JTableModelVariables\&.getRowCount ()"

.PP
Definition at line 45 of file JTableModelVariables\&.java\&.
.SS "Object sgs\&.model\&.other\&.JTableModelVariables\&.getValueAt (introw, intcol)"

.PP
Definition at line 56 of file JTableModelVariables\&.java\&.
.SS "\fBSingleVariable\fP sgs\&.model\&.other\&.JTableModelVariables\&.getVariableAt (introw)"

.PP
Definition at line 74 of file JTableModelVariables\&.java\&.
.SS "boolean sgs\&.model\&.other\&.JTableModelVariables\&.isCellEditable (introw, intcolumn)"

.PP
Definition at line 80 of file JTableModelVariables\&.java\&.
.SS "void sgs\&.model\&.other\&.JTableModelVariables\&.setValueAt (ObjectaValue, introw, intcol)"

.PP
Definition at line 50 of file JTableModelVariables\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
