.TH "sgs.model.gridObjects.House" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridObjects.House \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.gridObjects\&.Consumer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHouse\fP ()"
.br
.ti -1c
.RI "void \fBsetPowerDemand\fP (double powerDemand)"
.br
.ti -1c
.RI "void \fBsetProductionToWeatherAndTime\fP (GregorianCalendar currentTime, \fBWeather\fP weather)"
.br
.ti -1c
.RI "\fBGridDataEnum\fP \fBgetEnum\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBSmartGridObject\fP\&. 
.PP
\fBAuthor:\fP
.RS 4
tobi, Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 14 of file House\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.gridObjects\&.House\&.House ()"

.PP
Definition at line 21 of file House\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGridDataEnum\fP sgs\&.model\&.gridObjects\&.House\&.getEnum ()\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
corresponding enum for this object\&. 
.RE
.PP

.PP
Implements \fBsgs\&.model\&.gridObjects\&.SmartGridObject\fP\&.
.PP
Definition at line 89 of file House\&.java\&.
.SS "void sgs\&.model\&.gridObjects\&.House\&.setPowerDemand (doublepowerDemand)"

.PP
\fBParameters:\fP
.RS 4
\fIpowerDemand\fP 
.RE
.PP

.PP
Definition at line 30 of file House\&.java\&.
.SS "void sgs\&.model\&.gridObjects\&.House\&.setProductionToWeatherAndTime (GregorianCalendarcurrentTime, \fBWeather\fPweather)\fC [virtual]\fP"
TODO: move it ??
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
parsed number OR 0 at error 
.RE
.PP

.PP
Implements \fBsgs\&.model\&.gridObjects\&.SmartGridObject\fP\&.
.PP
Definition at line 84 of file House\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
