.TH "sgs.model.objectModels.PiEquivalentPowerLine" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.PiEquivalentPowerLine \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.objectModels\&.AbstractPowerLineModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPiEquivalentPowerLine\fP ()"
.br
.ti -1c
.RI "void \fBupdateVariables\fP (GregorianCalendar currentTime, \fBWeather\fP weather, int resolution)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitVariableSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Poechacker 
.RE
.PP

.PP
Definition at line 19 of file PiEquivalentPowerLine\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.objectModels\&.PiEquivalentPowerLine\&.PiEquivalentPowerLine ()"

.PP
Definition at line 29 of file PiEquivalentPowerLine\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.model\&.objectModels\&.PiEquivalentPowerLine\&.initVariableSet ()\fC [protected]\fP, \fC [virtual]\fP"
Implemented in the model and called in the constructor of an AbstractObjectnameModel super-class 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 47 of file PiEquivalentPowerLine\&.java\&.
.SS "void sgs\&.model\&.objectModels\&.PiEquivalentPowerLine\&.updateVariables (GregorianCalendarcurrentTime, \fBWeather\fPweather, intresolution)\fC [virtual]\fP"
Should be implemented in the model to calculate new variable values 
.PP
Implements \fBsgs\&.model\&.objectModels\&.AbstractModel\fP\&.
.PP
Definition at line 39 of file PiEquivalentPowerLine\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
