.TH "sgs.model.gridData.GridDataEnum.Type" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridData.GridDataEnum.Type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBICON\fP"
.br
.ti -1c
.RI "\fBMAP_LRUD\fP"
.br
.ti -1c
.RI "\fBMAP_LRU\fP"
.br
.ti -1c
.RI "\fBMAP_LRD\fP"
.br
.ti -1c
.RI "\fBMAP_LUD\fP"
.br
.ti -1c
.RI "\fBMAP_RUD\fP"
.br
.ti -1c
.RI "\fBMAP_LR\fP"
.br
.ti -1c
.RI "\fBMAP_UD\fP"
.br
.ti -1c
.RI "\fBMAP_LU\fP"
.br
.ti -1c
.RI "\fBMAP_RU\fP"
.br
.ti -1c
.RI "\fBMAP_RD\fP"
.br
.ti -1c
.RI "\fBMAP_LD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Map elements can be different depending on surrounding elements\&. 
.PP
.RS 4
An icon must always exist\&. Pure control icons do not have a map element\&. The default and minimum definition for a map elements is the
.PP
.RE
.PP
LeftRightUpDown type 'MAP_LRUD'\&.
.PP
Naming and order: 1\&.Left, 2\&.Right, 3\&.Up, 4\&.Down 
.PP
Definition at line 172 of file GridDataEnum\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.ICON"

.PP
Definition at line 174 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LD"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LR"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LRD"

.PP
Definition at line 176 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LRU"

.PP
Definition at line 176 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LRUD"

.PP
Definition at line 175 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LU"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_LUD"

.PP
Definition at line 176 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_RD"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_RU"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_RUD"

.PP
Definition at line 176 of file GridDataEnum\&.java\&.
.SS "sgs\&.model\&.gridData\&.GridDataEnum\&.Type\&.MAP_UD"

.PP
Definition at line 177 of file GridDataEnum\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
