.TH "sgs.view.JTableSGS" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.JTableSGS \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JTable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJTableSGS\fP (\fBVariableSet\fP variableSet)"
.br
.ti -1c
.RI "boolean \fBeditCellAt\fP (int row, int column, EventObject e)"
.br
.ti -1c
.RI "void \fBsetTableModelVariables\fP (\fBVariableSet\fP variableSet)"
.br
.in -1c
.SH "Detailed Description"
.PP 
JTable selecting all text on cell edit\&.
.PP
\fBAuthor:\fP
.RS 4
Kristofer Schweiger 
.RE
.PP

.PP
Definition at line 18 of file JTableSGS\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.JTableSGS\&.JTableSGS (\fBVariableSet\fPvariableSet)"

.PP
Definition at line 22 of file JTableSGS\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean sgs\&.view\&.JTableSGS\&.editCellAt (introw, intcolumn, EventObjecte)"

.PP
Definition at line 28 of file JTableSGS\&.java\&.
.SS "void sgs\&.view\&.JTableSGS\&.setTableModelVariables (\fBVariableSet\fPvariableSet)"

.PP
Definition at line 50 of file JTableSGS\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
