.TH "sgs.view.AboutDialog" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.view.AboutDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDialog\fP (JFrame parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file AboutDialog\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.view\&.AboutDialog\&.AboutDialog (JFrameparent)"

.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP

.PP
Definition at line 22 of file AboutDialog\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
