.TH "sgs.controller.interfaces.RuntimeListener" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.interfaces.RuntimeListener \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateDateAndTime\fP (\fBWeather\fP currentWeather, GregorianCalendar currentTime)"
.br
.in -1c
.SH "Detailed Description"
.PP 
watch over the interface 
.PP
Definition at line 11 of file RuntimeListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void sgs\&.controller\&.interfaces\&.RuntimeListener\&.updateDateAndTime (\fBWeather\fPcurrentWeather, GregorianCalendarcurrentTime)"
call, tells that current Weather and Time has Changed 
.PP
\fBParameters:\fP
.RS 4
\fIcurrentWeather\fP 
.br
\fIcurrentTime\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
