.TH "sgs.model.objectModels.AbstractWindPowerPlantModel" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.objectModels.AbstractWindPowerPlantModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsgs\&.model\&.objectModels\&.AbstractPowerPlantModel\fP\&.
.PP
Inherited by \fBsgs\&.model\&.objectModels\&.RandomWindTurbineModel\fP, and \fBsgs\&.model\&.objectModels\&.UsualWindTurbineModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractWindPowerPlantModel\fP (\fBWindTurbinePowerPlant\fP \fBpowerPlant\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
bbreilin 
.RE
.PP

.PP
Definition at line 9 of file AbstractWindPowerPlantModel\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sgs\&.model\&.objectModels\&.AbstractWindPowerPlantModel\&.AbstractWindPowerPlantModel (\fBWindTurbinePowerPlant\fPpowerPlant)"

.PP
Definition at line 12 of file AbstractWindPowerPlantModel\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
