.TH "sgs.controller.simulation.ACPowerFlowCalculator.busTypes" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.controller.simulation.ACPowerFlowCalculator.busTypes \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBREFERENCE_BUS\fP"
.br
.ti -1c
.RI "\fBLOAD_BUS\fP"
.br
.ti -1c
.RI "\fBGENERATOR_BUS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file ACPowerFlowCalculator\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "sgs\&.controller\&.simulation\&.ACPowerFlowCalculator\&.busTypes\&.GENERATOR_BUS"

.PP
Definition at line 70 of file ACPowerFlowCalculator\&.java\&.
.SS "sgs\&.controller\&.simulation\&.ACPowerFlowCalculator\&.busTypes\&.LOAD_BUS"

.PP
Definition at line 70 of file ACPowerFlowCalculator\&.java\&.
.SS "sgs\&.controller\&.simulation\&.ACPowerFlowCalculator\&.busTypes\&.REFERENCE_BUS"

.PP
Definition at line 70 of file ACPowerFlowCalculator\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
