.TH "sgs.model.gridObjects" 3 "Wed Oct 28 2015" "Version 0.92" "RAPSim" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgs.model.gridObjects \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnector\fP"
.br
.ti -1c
.RI "class \fBConsumer\fP"
.br
.ti -1c
.RI "class \fBCustomConsumer\fP"
.br
.ti -1c
.RI "class \fBCustomPowerPlant\fP"
.br
.ti -1c
.RI "class \fBFossilFuelPowerPlant\fP"
.br
.ti -1c
.RI "class \fBGridPower\fP"
.br
.ti -1c
.RI "class \fBHouse\fP"
.br
.ti -1c
.RI "class \fBPowerLine\fP"
.br
.ti -1c
.RI "class \fBPowerPlant\fP"
.br
.ti -1c
.RI "class \fBPowerTransport\fP"
.br
.ti -1c
.RI "class \fBProSumer\fP"
.br
.ti -1c
.RI "class \fBSmartGridObject\fP"
.br
.ti -1c
.RI "class \fBSolarPowerPlant\fP"
.br
.ti -1c
.RI "class \fBWindTurbinePowerPlant\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RAPSim from the source code\&.
